### ISSUE TITLE
Problem with Docker

### ISSUE THREAD

**Issue by buhino** [danielquinn/paperless#102]
Hi guys, at first sorry for my english.

I have testing paperless in debian 8 jessie in my home and work's fine but in the work i have a problem with the permissions (Ubuntu 14.04).

docker-compose --version
docker-compose version 1.6.2, build 4d72027

I have done the same steps in Ubuntu:

1. git clone https://github.com/danielquinn/paperless.git
2. Set the permissions to 777 for avoid problems in the directory where I have installed Paperless and the consumer directory.

        aalcantara@ea:~$ ls -l
        drwxrwxrwx 2 aalcantara aalcantara     4096 mar 30 10:12 consumer
        drwxrwxrwx 3 aalcantara aalcantara     4096 mar 30 10:12 pruebas

  (Paperless is in the directory pruebas)

3. Modify the docker-compose.yml. in ./pruebas. It looks the following aspect:

        version: '2'
        
        services:
            webserver:
                image: pitkley/paperless
                ports:
                    # You can adapt the port you want Paperless to listen on by
                    # modifying the part before the `:`.
                    - "8000:8000"
                volumes:
                    - data:/usr/src/paperless/data
                    - media:/usr/src/paperless/media
                env_file: docker-compose.env
                # The reason the line is here is so that the webserver that doesn't do
                # any text recognition and doesn't have to install unnecessary
                # languages the user might have set in the env-file by overwriting the
                # value with nothing.
                environment:
                    - PAPERLESS_OCR_LANGUAGES=
                command: ["runserver", "0.0.0.0:8000"]
        
            consumer:
                image: pitkley/paperless
                volumes:
                    - data:/usr/src/paperless/data
                    - media:/usr/src/paperless/media
                    # You have to adapt the local path you want the consumption
                    # directory to mount to by modifying the part before the ':'.
                    - /home/users/aalcantara/consumer/:/consume
                    # Likewise, you can add a local path to mount a directory for
                    # exporting. This is not strictly needed for paperless to
                    # function, only if you're exporting your files: uncomment
                    # it and fill in a local path if you know you're going to
                    # want to export your documents.
                    # - /path/to/another/arbitrary/place:/export
                env_file: docker-compose.env
                command: ["document_consumer"]
        
        volumes:
            data:
            media:
 
Now the differences between my Debian 8 and Ubuntu 14.04:

Debian 8:

    artion@debian:/opt/paperless$ docker-compose up
    Creating network "paperless_default" with the default driver
    Creating volume "paperless_media" with default driver
    Creating volume "paperless_data" with default driver
    Creating paperless_webserver_1
    Creating paperless_consumer_1
    Attaching to paperless_webserver_1, paperless_consumer_1
    consumer_1  | Starting document consumer at /consume

I have test to put a pdf in the consumer directory and the program upload automatic to the database.

Ubuntu 10.04 (the problem):

First execution (this morning I have deleted the old containers, images, old paperless directory and I start the process instalation again)

    aalcantara@ea:~/pruebas/paperless$ docker-compose up
    Creating volume "paperless_media" with default driver
    Creating volume "paperless_data" with default driver
    Pulling webserver (pitkley/paperless:latest)...
    latest: Pulling from pitkley/paperless
    fdd5d7827f33: Already exists
    a3ed95caeb02: Already exists
    0f35d0fe50cc: Already exists
    7b40647e93b7: Already exists
    ce5207842c4c: Already exists
    da7994e536a7: Already exists
    eb32bc956113: Already exists
    ff5cd3880712: Already exists
    765cf2d8b0ec: Pull complete
    8ff8cc61e674: Pull complete
    a373fe3a94bd: Pull complete
    5b7cb83830b4: Pull complete
    97ae97f8d0bd: Pull complete
    1d77a02fb8f3: Pull complete
    171ccfd2c7ab: Pull complete
    Digest: sha256:f3878a451aba47a774aa07719f9eeef4dfd351f62ad7f5a6a0f64a893966b410
    Status: Downloaded newer image for pitkley/paperless:latest
    Creating paperless_webserver_1
    Creating paperless_consumer_1
    Attaching to paperless_webserver_1, paperless_consumer_1
    consumer_1  | chgrp: changing group of ‘/consume’: Operation not permitted
    paperless_consumer_1 exited with code 1

Probably the mistake is in the chgrp and it will be easy to fix (I hope). I am watching the python scripts but i am a noob in this language.

I'm new in the git world :P, it's my first post and i dont have some experience with docker and scripting.

Thx so much and best reggards.

**Comment by pitkley** [comment]
Hi @buhino, thanks for posting your issue over here!

As I have mentioned in my mail to you, and as you have pointed out too, there seem to be some problems with permissions.

Can you execute the following commands on the Ubuntu 14.04 system? They should deliver similar output to what I have posted here:

```console
$ mkdir ~/permissiontest
$ docker run --rm -v ~/permissiontest:/permissiontest pitkley/paperless /bin/bash -c 'chgrp 1001 /permissiontest; ls -lAhnd /permissiontest'
drwxr-xr-x 2 1000 1001 4.0K Mar 29 17:04 /permissiontest
$ ls -lAhnd ~/permissiontest
drwxr-xr-x 2 ???? 1001 4.0K Mar 29 17:04 /permissiontest
```

**Comment by buhino** [comment]
aalcantara@ea:~$ mkdir ~/permissiontest
aalcantara@ea:~$ sudo docker run --rm -v ~/permissiontest:/permissiontest pitkley/paperless /bin/bash -c 'chgrp 1001 /permissiontest; ls -lAhnd /permissiontest'
[sudo] password for aalcantara: 
chgrp: changing group of ‘/permissiontest’: Operation not permitted
drwxrwxr-x 2 1038 1038 4.0K Mar 30 11:47 /permissiontest
aalcantara@ea:~$ ls -lAhnd ~/permissiontest
drwxrwxr-x 2 1038 1038 4,0K mar 30 13:47 /home/users/aalcantara/permissiontest

I dont understand why the chgrp dont works.

**Comment by pitkley** [comment]
Can you try to `sudo chgrp 1001 ~/permissiontest` directly on the host?

**Comment by buhino** [comment]
aalcantara@ea:~$ sudo chgrp 1001 ~/permissiontest
chgrp: cambiando el grupo de «/home/users/aalcantara/permissiontest»: Operación no permitida

:(

Maybe my boss limited my account or can be another reason??? I asked him and said to me that i have all the privileges. It's strange because following the same steps in my personal computer paperless works.

**Comment by pitkley** [comment]
What does `sudo chown aalcantara:1001 ~/permissiontest` do? What is the output of `lsattr -d ~/permissiontest`?

There seem to be some privilege issues, maybe something regarding the filesystem.

**Comment by buhino** [comment]
aalcantara@ea:~$ sudo chown aalcantara:1001 ~/permissiontest
[sudo] password for aalcantara: 
chown: cambiando el propietario de «/home/users/aalcantara/permissiontest»: Operación no permitida
aalcantara@ea:~$ lsattr -d ~/permissiontest
lsattr: Función ioctl no apropiada para el dispositivo Mientras se leían las banderas en /home/users/aalcantara/permissiontest

**Comment by pitkley** [comment]
Well, this is definitely not an issue with Paperless or Docker, but rather with how your system is set up. Can you get us the output for the following command:

```console
$ findmnt $(df ~/permissiontest | tail -1 | awk '{print $1}')
```

**Comment by buhino** [comment]
aalcantara@ea:~$ sudo findmnt $(df ~/permissiontest | tail -1 | awk '{print $1}')
TARGET                 SOURCE                         FSTYPE OPTIONS
/home/users/aalcantara prowler:/home/users/aalcantara nfs    rw,noatime,vers=3,rsize=32768,wsize=32768,namlen=255,h

**Comment by pitkley** [comment]
Yeah, so your home-directory is on a NFS volume and that doesn't allow adapting the group of the created directories.

I have opened a pull request (#103) which will output a warning instead of failing if changing the group or permissions fails. As soon as that is merged, you should be able to use Paperless on your Ubuntu machine.

This will require the permissions of the consumption-directory and the files in it to be adapted, but given the information in your initial post, you have already done so.

I'll ping you as soon as you can try again.

**Comment by buhino** [comment]
Many thanks for all pitkley. A last question, if I try to install paperless using the vagrantfile or the standart installation, i would have the same problem with the permissions?? I believe yes because is a host problem but It's only for explain to my boss.

**Comment by pitkley** [comment]
The new and hopefully fixed image is now on Docker Hub, so be sure to execute `docker pull pitkley/paperless` and try again.

> A last question, if I try to install paperless using the vagrantfile or the standart installation, i would have the same problem with the permissions??

Volumes with Vagrant are not as simple as with Docker, since Vagrant creates a complete virtual machine instead of a container. I don't know how mounting a host-directory into a Vagrant-VM works, but you probably would not have the same issues.

**Comment by buhino** [comment]
I have repeated the process without sucess althought the error continues now is more bigger xD

aalcantara@ea:/opt/paperless/paperless$ docker-compose up
Creating volume "paperless_media" with default driver
Creating volume "paperless_data" with default driver
Recreating paperless_webserver_1
Recreating paperless_consumer_1
Attaching to paperless_webserver_1, paperless_consumer_1
consumer_1  | chgrp: changing group of ‘/consume’: Operation not permitted
consumer_1  | Changing group of consumption directory:
consumer_1  |   /consume
consumer_1  | failed.
consumer_1  | 
consumer_1  | Either try to set it on your host-mounted directory
consumer_1  | directly, or make sure that the directory has `o+x`
consumer_1  | permissions and the files in it at least `o+r`.
consumer_1  | Starting document consumer at /consume
consumer_1  | Traceback (most recent call last):
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1  |     return self.cursor.execute(sql, params)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1  |     return Database.Cursor.execute(self, query, params)
consumer_1  | sqlite3.IntegrityError: NOT NULL constraint failed: documents_log.component
consumer_1  | 
consumer_1  | The above exception was the direct cause of the following exception:
consumer_1  | 
consumer_1  | Traceback (most recent call last):
consumer_1  |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1  |     execute_from_command_line(sys.argv)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
consumer_1  |     utility.execute()
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
consumer_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
consumer_1  |     self.execute(*args, **cmd_options)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
consumer_1  |     output = self.handle(*args, **options)
consumer_1  |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 50, in handle
consumer_1  |     "Starting document consumer at {}".format(settings.CONSUMPTION_DIR)
consumer_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1279, in info
consumer_1  |     self._log(INFO, msg, args, **kwargs)
consumer_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1415, in _log
consumer_1  |     self.handle(record)
consumer_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1425, in handle
consumer_1  |     self.callHandlers(record)
consumer_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
consumer_1  |     hdlr.handle(record)
consumer_1  |   File "/usr/local/lib/python3.5/logging/__init__.py", line 855, in handle
consumer_1  |     self.emit(record)
consumer_1  |   File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
consumer_1  |     Log.objects.create(**kwargs)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 401, in create
consumer_1  |     obj.save(force_insert=True, using=self.db)
consumer_1  |   File "/usr/src/paperless/src/documents/models.py", line 248, in save
consumer_1  |     models.Model.save(self, *args, **kwargs)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 700, in save
consumer_1  |     force_update=force_update, update_fields=update_fields)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 728, in save_base
consumer_1  |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 812, in _save_table
consumer_1  |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 851, in _do_insert
consumer_1  |     using=using, raw=raw)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1  |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1039, in _insert
consumer_1  |     return query.get_compiler(using=using).execute_sql(return_id)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
consumer_1  |     cursor.execute(sql, params)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
consumer_1  |     return super(CursorDebugWrapper, self).execute(sql, params)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1  |     return self.cursor.execute(sql, params)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
consumer_1  |     six.reraise(dj_exc_type, dj_exc_value, traceback)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
consumer_1  |     raise value.with_traceback(tb)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1  |     return self.cursor.execute(sql, params)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1  |     return Database.Cursor.execute(self, query, params)
consumer_1  | django.db.utils.IntegrityError: NOT NULL constraint failed: documents_log.component
paperless_consumer_1 exited with code 1

**Comment by danielquinn** [comment]
There were some changes made to the logging engine a few days ago and one of those changes was to drop a column.  If you haven't run `python manage.py migrate` on this instance, then that might be what's causing the problem.  Take a look at the [documentation](http://paperless.readthedocs.org/en/latest/migrating.html#updates), specifically the section about how to update in Docker and that might fix you up.

**Comment by buhino** [comment]
Hi again, i have returned to this proyect. Now i have installed paperless via docker in a VPS server, the consumer and webserver starts but when the consumer try to consume a pdf throws this:

consumer_1  | Consuming /consume/lmtp.pdf
consumer_1  | Generating greyscale image from /consume/lmtp.pdf
consumer_1  | convert: unable to open image `/consume/lmtp.pdf': Permission denied @ error/blob.c/OpenBlob/2709.
consumer_1  | convert: no images defined `/tmp/paperless/paperlesscpaul99z/convert-%04d.pnm' @ error/convert.c/ConvertImageCommand/3210.
consumer_1  | Generating the thumbnail
consumer_1  | convert: unable to open image `/consume/lmtp.pdf': Permission denied @ error/blob.c/OpenBlob/2709.
consumer_1  | convert: no images defined `/tmp/paperless/paperlesscpaul99z/convert-%04d.png' @ error/convert.c/ConvertImageCommand/3210.
consumer_1  | OCR FAILURE for /consume/lmtp.pdf: No images found

I have test different document and all with the same results :( . The last week in my home paperless worked fine with the same doccuments. What's happen¿?  Thx for be patients :P

**Comment by pitkley** [comment]
As mentioned in the [Paperless docs about Docker](https://paperless.readthedocs.org/en/latest/setup.html#docker-method) (in step 9):

> Make sure that the documents you put into the consumption directory will either be readable by everyone (`chmod o+r file.pdf`) or readable by the default user or group id 1000 (or the one you have set with `USERMAP_UID` or `USERMAP_GID` respectively).

**Comment by buhino** [comment]
>.< I forget this. Thx pit, now it work's fine. You can close the post

**Comment by pitkley** [comment]
I'm glad you got it working! :+1: 

You can close the issue yourself in the bottom right, or @danielquinn can close it too.
