### ISSUE TITLE
Problem making things a little more permanent

### ISSUE THREAD

**Issue by manderso7** [danielquinn/paperless#110]
Me again. Sorry.
Raspbian Jessie. Following the instructions to make things permanent, I've created the paperless user and group, enabled the services in /opt/paperless/scripts/*.service, but when I try and start consumer I get   `Failed to start opt-paperless-scripts-paperless\x2dconsumer.service.mount: Unit opt-paperless-scripts-paperless\x2dconsumer.service.mount failed to load: No such file or directory.`  I edited the consumer.service file and updated the path to the correct location, but I get the same error. What'd I do wrong?

**Comment by danielquinn** [comment]
If you edit the file, Systemd needs to be *told* that the file's been edited, or it will just re-execute the same stuff it did last time.  Try this:

```bash
systemctl daemon-reload
systemctl start paperless-consumer.service
```

**Comment by manderso7** [comment]
Thank you, I needed to do more research into systemctl apparently.
