### ISSUE TITLE
Created Date Not Set

### ISSUE THREAD

**Issue by bmartin5692** [danielquinn/paperless#121]
I've scanned ~100 docs into paperless now. I followed the guide for [Guesswork file naming](https://paperless.readthedocs.io/en/latest/guesswork.html), but the created date isn't being set properly when I specify the date. For example if the filename is: 20160428Z - Corr - Title - tag.pdf, the created date when the document is imported is set to the current date, not 2016-04-28.

Could this be an environmental issue or is it a bug?

**Comment by danielquinn** [comment]
Interesting, because the [tests](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py#L140) should be accounting for just this case.  I'll do some tests of my own using the file name you describe and see if I can reproduce it.  But yeah, it sounds like a bug.

**Comment by danielquinn** [comment]
Thanks for catching that!  I know it took a long time, but it's finally fixed :-)
