### ISSUE TITLE
Variable for density

### ISSUE THREAD

**Issue by bmartin5692** [danielquinn/paperless#122]
I've found that by changing the density from 300 to 200, my documents are imaged faster, the OCR results are about as accurate, and the temporary files are ~1/3 the size. 

I'd propose adding a variable for the config file to make it easier for users to adjust without editing the source.

**Comment by danielquinn** [comment]
This sounds perfectly reasonable.  I'll add it to the TODO list.  If you've got time to write a PR though, I'm happy to accept it.

**Comment by bmartin5692** [comment]
I've submitted a pull request for this option. See PR #124 .

**Comment by danielquinn** [comment]
Closing since I've merged #124.
