### ISSUE TITLE
Can't install requirements on RPI

### ISSUE THREAD

**Issue by brandonskerritt51** [danielquinn/paperless#126]
Hi! i'm having a slight issue installing the requirements on RPI.
I'm using the code
`pip install --user --requirement /path/to/paperless/requirements.txt`
found within the documentation, replacing /path/to/paperless with the actual path but i'm getting an error. The requirements installed fine on my Mac :-( 

here is the full install of requirements along with error at bottom (it's a python error)
Alternatively, here's [pastebin](http://pastebin.com/jW6SwQxy) of the error

`pi@raspberrypi:~/Desktop/paperless $ pip install --user --requirement requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Django==1.9.4 in /home/pi/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Downloading/unpacking Pillow==3.1.1 (from -r requirements.txt (line 2))
  Downloading Pillow-3.1.1.zip (10.4MB): 10.4MB downloaded
  Running setup.py (path:/tmp/pip-build-B2Fyuh/Pillow/setup.py) egg_info for package Pillow

    warning: no previously-included files found matching '.editorconfig'
Downloading/unpacking django-crispy-forms==1.6.0 (from -r requirements.txt (line 3))
  Downloading django_crispy_forms-1.6.0-py2-none-any.whl (178kB): 178kB downloaded
Downloading/unpacking django-extensions==1.6.1 (from -r requirements.txt (line 4))
  Downloading django_extensions-1.6.1-py2.py3-none-any.whl (202kB): 202kB downloaded
Downloading/unpacking django-filter==0.12.0 (from -r requirements.txt (line 5))
  Downloading django_filter-0.12.0-py2.py3-none-any.whl
Downloading/unpacking djangorestframework==3.3.2 (from -r requirements.txt (line 6))
  Downloading djangorestframework-3.3.2-py2.py3-none-any.whl (634kB): 634kB downloaded
Downloading/unpacking filemagic==1.6 (from -r requirements.txt (line 7))
  Downloading filemagic-1.6.tar.gz
  Running setup.py (path:/tmp/pip-build-B2Fyuh/filemagic/setup.py) egg_info for package filemagic

Downloading/unpacking langdetect==1.0.5 (from -r requirements.txt (line 8))
  Downloading langdetect-1.0.5.zip (993kB): 993kB downloaded
  Running setup.py (path:/tmp/pip-build-B2Fyuh/langdetect/setup.py) egg_info for package langdetect

Downloading/unpacking pyocr==0.3.1 (from -r requirements.txt (line 9))
  Downloading pyocr-0.3.1.tar.gz
  Running setup.py (path:/tmp/pip-build-B2Fyuh/pyocr/setup.py) egg_info for package pyocr

Downloading/unpacking python-dateutil==2.4.2 (from -r requirements.txt (line 10))
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB): 188kB downloaded
Downloading/unpacking python-dotenv==0.3.0 (from -r requirements.txt (line 11))
  Downloading python_dotenv-0.3.0-py2.py3-none-any.whl
Downloading/unpacking python-gnupg==0.3.8 (from -r requirements.txt (line 12))
  Downloading python-gnupg-0.3.8.tar.gz
  Running setup.py (path:/tmp/pip-build-B2Fyuh/python-gnupg/setup.py) egg_info for package python-gnupg

Downloading/unpacking pytz==2015.7 (from -r requirements.txt (line 13))
  Downloading pytz-2015.7-py2.py3-none-any.whl (476kB): 476kB downloaded
Requirement already satisfied (use --upgrade to upgrade): six>=1.2 in /usr/lib/python2.7/dist-packages (from django-extensions==1.6.1->-r requirements.txt (line 4))
Downloading/unpacking ordereddict (from python-dotenv==0.3.0->-r requirements.txt (line 11))
  Downloading ordereddict-1.1.tar.gz
  Running setup.py (path:/tmp/pip-build-B2Fyuh/ordereddict/setup.py) egg_info for package ordereddict

Downloading/unpacking click>=5.0 (from python-dotenv==0.3.0->-r requirements.txt (line 11))
  Downloading click-6.6.tar.gz (283kB): 283kB downloaded
  Running setup.py (path:/tmp/pip-build-B2Fyuh/click/setup.py) egg_info for package click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Installing collected packages: Pillow, django-crispy-forms, django-extensions, django-filter, djangorestframework, filemagic, langdetect, pyocr, python-dateutil, python-dotenv, python-gnupg, pytz, ordereddict, click
  Running setup.py install for Pillow

    warning: no previously-included files found matching '.editorconfig'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-B2Fyuh/Pillow/setup.py", line 767, in <module>
        zip_safe=not debug_build(),
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/tmp/pip-build-B2Fyuh/Pillow/setup.py", line 516, in build_extensions
        (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-B2Fyuh/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FwGYHs-record/install-record.txt --single-version-externally-managed --compile --user:
    running install

running build

running build_py

creating build

creating build/lib.linux-armv7l-2.7

creating build/lib.linux-armv7l-2.7/PIL

copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageTransform.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/FontFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageChops.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/GdImageFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageOps.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ContainerIO.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageWin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/TarIO.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageMorph.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/WalImageFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageCms.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageFilter.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/JpegPresets.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageTk.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageQt.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ExifTags.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageDraw.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/OleFileIO.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/_binary.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImagePath.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageStat.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/_util.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImagePalette.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageFont.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/TiffTags.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageColor.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageMode.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/__init__.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageGrab.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PyAccess.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PaletteFile.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/Image.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageMath.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/PSDraw.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageSequence.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageShow.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/features.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-2.7/PIL

copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-2.7/PIL

running egg_info

writing Pillow.egg-info/PKG-INFO

writing top-level names to Pillow.egg-info/top_level.txt

writing dependency_links to Pillow.egg-info/dependency_links.txt

warning: manifest_maker: standard file '-c' not found

reading manifest file 'Pillow.egg-info/SOURCES.txt'

reading manifest template 'MANIFEST.in'

warning: no previously-included files found matching '.editorconfig'

writing manifest file 'Pillow.egg-info/SOURCES.txt'

copying PIL/OleFileIO-README.md -> build/lib.linux-armv7l-2.7/PIL

running build_ext

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-B2Fyuh/Pillow/setup.py", line 767, in <module>

    zip_safe=not debug_build(),

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/tmp/pip-build-B2Fyuh/Pillow/setup.py", line 516, in build_extensions

    (f, f))

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-B2Fyuh/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FwGYHs-record/install-record.txt --single-version-externally-managed --compile --user failed with error code 1 in /tmp/pip-build-B2Fyuh/Pillow
Storing debug log for failure in /home/pi/.pip/pip.log`

**Comment by pitkley** [comment]
This issue is probably the same as in this [StackOverflow question](https://stackoverflow.com/questions/34631806/fail-during-installation-of-pillow-python-module-in-linux/34631976). The [highest voted answer](http://stackoverflow.com/a/34631976/758165) suggests installing the following packages:

```console
$ sudo apt-get install libtiff4-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.5-dev tk8.5-dev python-tk
```

This was specifically mentioned for Raspbian Wheezy 7.0, your result may vary if you are running Jessie or a different image altogether.

**Comment by PhyberApex** [comment]
Also please take care for which python you are using. You seem to be using 2.7. Paperless works with python3.

**Comment by brandonskerritt51** [comment]
@pitkley that fixed it, and so did @PhyberApex . Thank you for your help :)
