### ISSUE TITLE
OCR optimize - hook before file is consumed

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#130]
I evaluated how to optimize the scanned documents to get better OCR results.
I found textcleaner which works very well. (but needs a long time for conversion...)
http://www.fmwconcepts.com/imagemagick/textcleaner/
What do you use?

Based on that I am looking for a possibility to hook a short shell script at the beginning of the consumption process?

**Comment by danielquinn** [comment]
Hmm, it sounds like what you need is @phryneas' new [addition](https://github.com/danielquinn/paperless/pull/127) of a pre-consume hook script.  I merged those changes just last week (so update your local copy) and I just documented the feature now.  Read all about it [here](https://paperless.readthedocs.io/en/latest/consumption.html#hooking-into-the-consumption-process).

**Comment by Ulli2k** [comment]
is it possible to update the document filename within the hook function?

**Comment by danielquinn** [comment]
Not at the moment, no.  The script is executed on the file name, but doesn't return anything into the consumer itself.
