### ISSUE TITLE
Running Paperless on Synology Diskstation 212+

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#133]
I spend a lot of time to get paperless running on my Diskstation.
Therefore I want to share my positiv results to get it running:

I tried oPkg and iPkg without positive results.
The only way was to use Debian-Chroot (https://github.com/SynoCommunity/spksrc/wiki/Debian-Chroot)
# start chroot in the diskstation shell

```
sudo /var/packages/debian-chroot/scripts/start-stop-status chroot
```
# Share Folder SynologyOS<->Chroot Debian

```
nano /var/packages/debian-chroot/scripts/start-stop-status
  add --> grep -q "${CHROOTTARGET}/mnt/public " `realpath /volume1/public` || mount -o bind `realpath /volume1/public` ${CHROOTTARGET}/mnt/public
    add --> umount ${CHROOTTARGET}/mnt/public
```
# install zlib

```
wget http://http.debian.net/debian/pool/main/z/zlib/zlib_1.2.8.dfsg.orig.tar.gz
tar xvf zlib_1.2.8.dfsg.orig.tar.gz
./configure
make
make install
```
# install libjpeg & libtiff

```
nano /etc/apt/sources.list
    deb http://ftp.de.debian.org/debian jessie main 
apt-get update
apt-get install libjpeg-dev libtiff-dev
```
# Papierless

```
https://paperless.readthedocs.io/en/latest/setup.html

apt-get install python3 python3-dev python3-pip git ghostscript imagemagick tesseract-ocr tesseract-ocr-deu unpaper
cd /opt
git clone https://github.com/danielquinn/paperless.git
python3 -m pip install  --user --requirement /opt/paperless/requirements.txt
cp /opt/paperless/paperless.conf.example /etc/paperless.conf
nano /etc/papierless.conf # for configuration
```

**Comment by danielquinn** [comment]
Neat!  If you like, you can submit this as a PR for the documentation under [Installation & Configuration](https://paperless.readthedocs.io/en/latest/setup.html#installation-configuration)

**Comment by iFloris** [comment]
Pretty nice. But I think it is easier for most use cases to use the docker container (and compose env yml) instead.

**Comment by danielquinn** [comment]
Hi @Ulli2k, were you planning on sending me a PR for this or should I just close it?

**Comment by Ulli2k** [comment]
No, I guess it can be found in the issue list for people who need that information.
