### ISSUE TITLE
Square Cash for donations?

### ISSUE THREAD

**Issue by todrobbins** [danielquinn/paperless#134]
What about [Square Cash](https://cash.me) for donations as another alternative to Bitcoin? I like that it's direct from my bank account to yours. Just a thought that hopefully hasn't been addressed before.

**Comment by danielquinn** [comment]
Always nice to hear that people are trying to send me money :-)  Unfortunately though, that feels a little too much like making this a business and I don't think I have the energy for that.  I'll tell you what, if you wanna help out, I'd love to accept a pull request, or if money is your thing, donate to an environmental charity or something.  The climate needs your money more than I do :-)
