### ISSUE TITLE
Paperless WSGI (config suggestion)

### ISSUE THREAD

**Issue by steckerhalter** [danielquinn/paperless#144]
Hi

I tried making `paperless` work with Apache and WSGI. Maybe we could gather/discuss the necessary configs for different webservers and add them to the readme?

This is for a `virtualenv` setup with the user `paperless`:

```apache
<VirtualHost *:80>
    ServerName example.com

    Alias /static/ /home/paperless/paperless/static/
    <Directory /home/paperless/paperless/static>
        Require all granted
    </Directory>

    WSGIScriptAlias / /home/paperless/paperless/src/paperless/wsgi.py
    WSGIDaemonProcess example.com user=paperless group=paperless threads=5 python-path=/home/paperless/paperless/src:/home/paperless/.env/lib/python3.4/site-packages
    WSGIProcessGroup example.com

    <Directory /home/paperless/paperless/src/paperless>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>
</VirtualHost>
```

The static files have to be generated like that:

```bash
paperless@example:~$ /home/paperless/.env/bin/python /home/paperless/paperless/src/manage.py collectstatic 
```

It seems to work allright.

**Comment by danielquinn** [comment]
This seemed like a good idea, so [I've added it to the documentation](https://paperless.readthedocs.io/en/latest/setup.html#using-a-real-webserver).  Specifically, your part is [here](https://paperless.readthedocs.io/en/latest/setup.html#apache).

Thanks for the idea!

**Comment by steckerhalter** [comment]
@danielquinn you're welcome, thanks as well

**Comment by Ulli2k** [comment]
@steckerhalter: did you recognized a big performance improvement or what is the reason for using apache instead of the python server?

**Comment by steckerhalter** [comment]
@Ulli2k No, but it's easier for me since like this Apache is managing everything and I don't need to run a webserver instance.
