### ISSUE TITLE
Exporter crashes due to FileNotFoundError

### ISSUE THREAD

**Issue by iFloris** [danielquinn/paperless#155]
```
Exporting: /export/20130718173500-20130718193450.pdf
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 53, in handle
    self.dump()
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 70, in dump
    f.write(GnuPG.decrypted(document.source_file))
  File "/usr/src/paperless/src/documents/models.py", line 197, in source_file
    return open(self.source_path, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/src/../media/documents/originals/0000997.pdf.gpg'

```

I want to set up an hourly export, but I cannot get past this single file (nº 993 of a little over 3000 docs) which obviously is not very handy. Any help would be appreciated. I already used docker CP to copy the media/documents/originals, but of course those are GPG'ed.

**Comment by danielquinn** [comment]
From that error, am I correct in assuming that you have a record 993 in your database, but no corresponding .pdf file?  If that's the case, it would mean that the file was somehow deleted at some stage, without removing the db record.  The only solution then would be to delete the offending db record with:

```bash
./manage.py shell
from documents.models import Document
Document.objects.get(pk=993).delete()
```

...I think that's all you should need to do, assuming that 993 is the only one with thisproblem.

**Comment by iFloris** [comment]
Thanks @danielquinn for your fast reply, I will give that a shot! I am not sure why / how that file would be deleted; so there is possibly some data loss here. Is there a way to check what the paperless thinks that the contents of record 993 are?

**Comment by danielquinn** [comment]
Sure.  As the database record is still there, you should be able to open it up in the UI and read the title, correspondent, and the text pulled out via OCR.

It may also be a problem with the exporter?  If it's not yet smart enough to detect image documents and is instead assuming that all documents are pdfs, then this error message may be popping up where there never was a .pdf file, just a .jpg or something.

As the files are named sequentially, it should be easy to get a list of "files the db thinks exist" vs. "files that actually exist".  Just compare a directory listing to the output of `Document.objects.all().values_list("pk", flat=True") and see what might be missing.

**Comment by iFloris** [comment]
Thanks again @danielquinn 👍 

So using /document/993/change/ in the django interface I found the file that it gets stuck on. As you suggested it is indeed a jpeg (which it correctly OCR'd). Strange thing is that it is actually 'in' the export-folder, I presume as the last file to be exported. So it is there.. 

This is the file, in case you want to take a look:
![20111208082425-20111208093448_00004](https://cloud.githubusercontent.com/assets/252882/18448103/f6cb4982-7929-11e6-8ea3-017768c4fb12.jpg)
There are lots of other jpg's in the export folder as well.

I am going to try to delete the db record next and see where that gets me.
