### ISSUE TITLE
Matching does not work on upper words

### ISSUE THREAD

**Issue by CkuT** [danielquinn/paperless#157]
Hi !

I am trying to add new tags but it seems that the upper words of my documents (like "FOO") are not matched with the `MATCH_ANY` algorithm. 

There is 3 solutions that are currently coming to my mind :

- Match with a case-insensitive regex
- Do not lower() the match field when saving a match model
- Lower all the OCR content

What do you think about it ?

**Comment by danielquinn** [comment]
I like it, but there's the problem that this would change the current behaviour for anyone currently using `MATCH_ANY`.  It's not a difficult fix to force the match to go with all lowercase stuff, but I think a better option would be to introduce an additional `is_insensitive` flag to the the `Match` model, so users can explicitly choose case insensitivity.

So yes, I like this idea, but I don't have a lot of time these days as I'm buried in another project.  If however you really want this feature, feel free to send a pull request using an `is_insensitive` flag and I'll merge it.

**Comment by CkuT** [comment]
Would something like that : 8f2aadf be good for you ?

**Comment by danielquinn** [comment]
Thanks!  And the commit looks good save for one thing: I don't think the `save()` should be contain the conforming to `.lower()` as you've done here.  It changes the user's input so when she goes back to the admin, what she put in isn't there anymore.

Instead, I'd suggest tweaking `matches()` to have something like:

```python
search_kwargs = {}
if self.is_insensitive:
    search_kwargs = {"flags": re.IGNORECASE}
...
re.search(r"\b{}\b".format(word), text, **search_kwargs):  # and the other lines like this one
```

This will do a case insensitive search while preserving the user input.

What do you think?

**Comment by CkuT** [comment]
You are right, it is a good idea ! I will fix this as soon I will have a bit more of time to code ;)

**Comment by CkuT** [comment]
I updated my code ! 2c8e266

**Comment by danielquinn** [comment]
Thanks for your contribution :-)  I've merged your PR, so I'm going to assume I can close this now.  If not, please feel free to re-open it.
