### ISSUE TITLE
Feature request: Status indication in web gui

### ISSUE THREAD

**Issue by jat255** [danielquinn/paperless#16]
It would be great if there were some sort of indication in the GUI as to what was happening at any given time. i.e. ''Idle", "Consuming `name of file` X of N pages completed", etc.

Unfortunately I have no experience with django, so this is really just a request, as I don't think I'd be able to implement something like this myself.

**Comment by danielquinn** [comment]
This is a neat idea, but difficult to implement cleanly in the Django admin.  I think I might be able to hack out a sort of "consumption log" thing, and I could probably add some Javascript to the admin to have a sort of "growl-like" interface...  I'm not sure, but I like this idea.  I'm going to mark it as "feature" and leave it open for a bit while I think about it though.

**Comment by danielquinn** [comment]
Well this is here now, but the way we're doing logging kind of sucks.  I'm going to open a new issue for improving logging and close this one.
