### ISSUE TITLE
Files not transferred to PAPERLESS_MEDIADIR directory

### ISSUE THREAD

**Issue by mrjack711** [danielquinn/paperless#162]
Hi,

I've got paperless setup on Ubuntu server 16.04 using the bare metal approach and Systemd.
All is working fine with the default options.

I've enabled the `PAPERLESS_MEDIADIR` option in`/etc/paperless.conf` to a custom location:
`PAPERLESS_MEDIADIR="/media/documents"`

The file no longer gets transferred here after consumption. The file gets consumed and appears in the application, but stays in the consumption directory and clicking on the PDF icon for that document gives a FileNotFoundError page.

I've made sure the permissions and owner/group of the new directory is the same as the original media directory but i don't really know what else to change.

Any help would be appreciated
Thanks

**Comment by danielquinn** [comment]
It's tough to know without a little more digging around in your setup, so I'd suggest the following:

* Enter your virtualenv and `cd` into `paperless-root/src`.
* Run `./manage.py shell`.  This will get you into a Python shell for your Paperless installation.
* Type the following to get the value of `MEDIA_ROOT`, which is the place where Paperless thinks it should be writing your documents after consumption:

        from django.conf import settings
        print(settings.MEDIA_ROOT)

    *Hopefully* the output will tell you something about how you've configured Paperless.  If however MEDIA_ROOT is in fact set to `/media/documents`, then I'm left wondering if the configuration has been reloaded yet.  If you haven't already, restart paperless with `systemctl restart paperless-consumer.service` and `systemctl restart paperless-webserver.service` just for good measure.  At the very least that will ensure that it's using the right values.

If none of this helps, my next step is to start having you dig into the code where the value gets used and printing stuff out just to see what happens.

**Comment by danielquinn** [comment]
Given the lack of response, I'm going to assume that this is all ok now.
