### ISSUE TITLE
django-rest-framework-filters MethodFilter depricated

### ISSUE THREAD

**Issue by schober-ch** [danielquinn/paperless#164]
Hi,

the MethodFilter used in documents/filters.py is depreciated in the current release of django-rest-framework-filters (https://github.com/philipn/django-rest-framework-filters) and therefore paperless fails.

I'm not really familiar with the whole rest-framework-filtering stuff and would rather not try to fix it (now), since I guess its rather easy if one knows what they do and how they interact (too much magic in there...).

The quick fix I'm using at the moment is to fix the old versions of the related packages (django-rest-framework-filters, django-filter and django_restframework).

Let me know if it is more work to do than I anticipated, then I'll look into it, but might take some time.

**Comment by danielquinn** [comment]
The easiest fix for this would be to fix `requirements.txt` to set `djangorestframework` to `==3.4.4`.  It's a version I know works, and will prevent this sort of breakage for the moment, so that's what I've done.  However, this isn't a good fix since it limits Paperless to old software, so I'll leave this bug open to patch the Paperless codebase to play nice with the new rest framework changes.

In the mean time however, doing the following should get you back on your feet:

```
git pull
pip install -r requirements.txt
```

Then just restart Paperless (however you're running it) and you should be ok.

**Comment by schober-ch** [comment]
Thank you for your answer! I already 'fixed' it in the way you suggested :-) 

I'm currently working on some changes (tag colours and some others). Perhaps on the way I need to understand some of the REST-things anyway and can try to fix this. If I start looking into this I'll comment in this issue again, could you do the same so we do not do double work? 

And btw thanks, I really appreciate your project, mayan-edms was way too complicated for private documents.

**Comment by danielquinn** [comment]
Hey thanks for the compliment.  To tell you the truth, discovering mayan-edms really killed most of my enthusiasm for Paperless, so it's nice to see that it has some fans regardless.

I'll let you know if/when I start tweaking the code to handle the django-rest-framework deprecations.

**Comment by schober-ch** [comment]
slightly off-topic: I started with mayan-edms for my private "paperless office", but found it far to complicated and more tailored to (enterprise) document storage with all the subsequent requirements. Also, an issue with the thumbnail generation (https://gitlab.com/mayan-edms/mayan-edms/issues/259) killed all my motivation to use it. 
Therefore I hope to be able to adapt your project and maybe "polish" some of the things. I'll create a pull request if I finish something usable

**Comment by danielquinn** [comment]
I'm happy to accept pull requests!  Just please make sure that your code is (a) unit-tested and (b) conforms to pep8.

**Comment by danielquinn** [comment]
All the details are in the commit, but this should be working now.
