### ISSUE TITLE
Setup Question

### ISSUE THREAD

**Issue by Mirabis** [danielquinn/paperless#166]
Hi,

I purchased a Brother ADS 1100W scanner to use with paperless but kind of lost with the initial setup.

When scanning to FTP, do I use a 'OCR scan' or just a regular '600dpi' scap to the folder, after which paperless will do all the OCR/searchable text?

**Comment by danielquinn** [comment]
The "OCR scan" is (as far as I understand) a feature of the *Windows-based scanning client* and requires your computer to be on at the time of scanning -- not exactly what I wanted when I came up with Paperless.  No, all you need is a standard rasterised image, so 600dpi (or even 300 or 150) and have it scan to FTP into the directory that Paperless is consuming from.

Does that help?

**Comment by Mirabis** [comment]
Okay, thanks :) 

Went through the manual and it kept stating, for OCR setup a target application.. so started doubting whether it should use that or not.

Thanks for the quick reply.
