### ISSUE TITLE
Can attempt to process partially written scan

### ISSUE THREAD

**Issue by nigelm** [danielquinn/paperless#168]
I am using a scanner to write a PDF to a CIFS share which is exposed to paperless as a locally mounted directory.  The scanner writes the PDF a page at a time - so the file initially appears as an incomplete or even invalid file, and is completed later.

Paperless tries to process the file early on, runs into trouble because the number of pages in the PDF is inconsistent, and then fails in processing and ignores the file until the `document_consumer` is restarted.

Would it be possible to do one or more of the following:-

- Hold off on a new file until it has not been modified for n minutes (issues with time sync possible)
- When processing fails, requeue and try again after a delay, with a limit to prevent looping for ever
- Locking?  Not sure how this will work with various filesystem presentations

**Comment by danielquinn** [comment]
I've got some [rudimentary locking](https://github.com/danielquinn/paperless/blob/master/src/documents/consumer.py#L343) already in there, but from your description, I'm thinking that it's taking longer than `documents.management.commands.document_consumer.Command.LOOP_TIME` seconds to update, so Paperless is mistakenly assuming that the file is ready.  If you could try extending `LOOP_TIME` to something like `360` (5 minutes) and see if that works, we can change this value to be configurable.

**Comment by nigelm** [comment]
I increased the `LOOP_TIME` to 45 seconds which is a bit more than the time needed to feed or flip (if duplex) and scan a page, which helps considerably - so far no problems on a smallish number of multi-page scans.

I have also slightly modified the `_is_ready` method to use both file size and mtime (previously just used mtime - not the size) as I have found in previous projects that mtime can have update issues especially where networked file systems are anywhere near the system).

Will leave it running for a while to see how it goes.  Having `LOOP_TIME` configurable would also be useful.

**Comment by danielquinn** [comment]
If you can make your changes to `_ready()` available as a pull request, I'm happy to merge that, and I'll see about making LOOP_TIME configurable.  At the moment, I'm taking the afternoon to get the django_filters module up to date (they broke the API with the latest version).

**Comment by nigelm** [comment]
Apologies for the delay - the upside is I have now got my somewhat ad-hoc installation on FreeNAS (in a jail) working as a rather more repeatable automated install...

The changes in `LOOP_TIME` and exposure into the config file in 0.3 have made everything work out of the box for me with no additional changes outside the config file.

I think you can close this as is.

**Comment by danielquinn** [comment]
Cool beans!  I'm glad it's working for you.
