### ISSUE TITLE
document_consumer does not ask for passphrase

### ISSUE THREAD

**Issue by mkonstapel** [danielquinn/paperless#17]
I'm currently running it with no PASSPHRASE in settings.py. However, manage.py checks for the wrong command name:

```python
if "runserver" in sys.argv or "consume" in sys.argv:
```

This doesn't cause any visible errors, but all stored PDFs are 0 bytes.

Quick fix: make it check for "document_consumer" instead.

**Comment by danielquinn** [comment]
Thanks for noticing that!
