### ISSUE TITLE
Allow HTTP Basic auth for /fetch endpoints

### ISSUE THREAD

**Issue by thomasbrueggemann** [danielquinn/paperless#178]
Probably by pulling the /fetch functionality under the DjangoRestFrameworks scope.
Currently the FetchView can only be reached via SessionAuthentication login.

_I am new to Django but would love to contribute to this instead of just nagging about it 🙂_

**Comment by danielquinn** [comment]
Well diving into DjangoRestFramework may not be the easiest way to learn Django, but I'm more than happy to let you try :-)  If you're reasonably adept at Python, it shouldn't be too much to handle.

I'll assign this one to you, and feel free to post questions here if you have any.
