### ISSUE TITLE
go back to old look

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#191]
Hi,
a just did an update and do really not like the new thumbnail look in the document folder.
Is there a chance to go back to a list view with small thumbnail in one column?

**Comment by danielquinn** [comment]
Yeah I was afraid someone would say that.  Here's what I'm going to do:

* I **will** tell you how to get back the old look: just comment out these [two](https://github.com/danielquinn/paperless/blob/master/src/documents/templatetags/hacks.py#L38) [lines](https://github.com/danielquinn/paperless/blob/master/src/documents/templatetags/hacks.py#L39) and restart the webserver.
* I **won't** support this with a configuration flag as I have no interest in maintaining code for two interfaces.
* I **will** welcome any ideas & pull requests to improve the UI in a unified way.  That is, styles that mean only one interface needs to be maintained.
* I **will** welcome criticism about usability of the current interface.  Gods know I'm not UX expert, so help here is always welcome.  With that said though, I thought that listing thumbnails like that in a tabular setting was ugly and hard to use on both desktop & mobile, while the new layout works well on both.

I'm sorry you don't like the new layout, but that's the beauty of Free Software.  If you don't like it, fork & change it :-)

**Comment by Ulli2k** [comment]
Would it be possible to make the "change_list_results.html" file configureable?
e.g.
> if context["cl"].model == Document:
> path = os.getenv("PAPERLESS_LIST_RESULTS")

Everybody could adapt the listview and still pull updates from your github. :)
