### ISSUE TITLE
Additional Feature: Reminders for Documents

### ISSUE THREAD

**Issue by philippeowagner** [danielquinn/paperless#199]
@thomasbrueggemann filed an idea of adding reminders to documents [here](https://github.com/thomasbrueggemann/paperless-desktop/issues/4). I really like the idea. What do you think @danielquinn ?

**Comment by danielquinn** [comment]
I'm a little unclear as to what "reminders" means in this context.  Are we talking just a bit of text attached to a document with a time attached to it, or something more elaborate?

**Comment by philippeowagner** [comment]
From me a date (or datetime) field after the [modification date](https://github.com/danielquinn/paperless/blob/master/src/documents/models.py#L182) on the document would do the trick.

**Comment by danielquinn** [comment]
Well that would only allow one reminder per document and wouldn't offer any context for the reminder so if that's all you need, I'd probably go a little further and create a `Reminder` model and attach it to `Document` with a `ForeignKey` just so I don't end up having to rejig things later.

The trouble is that this would be a feature that'd be really hard to make use of on the web interface.  I could make it available via the API so Paperless Desktop could make use of it, but I don't think I have the energy to write a JS-based reminder thingy for the web application.

I suppose it's not a big deal though, as not everything developed for Paperless should necessarily be made available through web.

**Comment by philippeowagner** [comment]
Evernote goes with the simple one datetime solution and it works for me. 

Sure, having a Reminder object is the more elaborated and sustainable solution. 👍 

Having this in the API would be a great option. Other services could use this for other use cases als well, e.g. for sending reminders and/or documents by email.

**Comment by thomasbrueggemann** [comment]
I actually saw this implemented here https://www.fileee.com
They just allow to set a DateTime as a reminder/alarm and if that point in time is reached, the document appears on a special "inbox" page to remind you, that you have to pay a bill or whatever you scanned and want to postpone/be reminded of.

There it literally means to store one more DateTime and just present the document differently when "its time has come".

**Comment by danielquinn** [comment]
Ok I've just written the basics of reminders into 0.4.0 (releasing in a few minutes via #203).  This doesn't really have any effect on other people's Paperless installations, as it just adds this new reminders component to the database & API.  However, if you're doing something that plugs into Paperless, then this should be handy :-)

**Comment by philippeowagner** [comment]
Thank you @danielquinn for implementing reminders!
