### ISSUE TITLE
Deskew/Despeckle

### ISSUE THREAD

**Issue by rileytg** [danielquinn/paperless#20]
Often times when scanning documents (especially in bulk) you run into situations where the document is slightly skewed and/or has speckles that throw off OCR.

![skew](http://www.verypdf.com/wordpress/wp-content/uploads/2015/04/image_thumb6.png)
![speckle](http://www.fmwconcepts.com/misc_tests/cc_noise_remove/jx8MPc9_kuw2_lat10.png)

**Comment by rileytg** [comment]
Just opening this issue for thoughts on how to automatically process for this. There are a number of commercial products but I haven't found anything OSS that I've gotten to work well

**Comment by danielquinn** [comment]
I hear that [unpaper](https://www.flameeyes.eu/projects/unpaper) is the go-to tool for this sort of thing, but integrating it would have to be done on the command-line level (like we're already doing for Tesseract).  I'm not opposed to this, but given that all of my scans so far have been really good quality, I'm not prioritising it.

However, if someone wants to write a PR to make this work, I'd probably merge it :-)

**Comment by strages** [comment]
This would be incredible!

**Comment by pitkley** [comment]
Just to keep you guys in the loop: I have a working version of Paperless with `unpaper` which you can find over at [`feature/unpaper`](https://github.com/pitkley/paperless/tree/feature/unpaper).
This PR is currently blocked by #34, but as soon as that is resolved I will open a PR for `unpaper`.

I did some limited testing (mainly because I don't have any bad scan samples at hand), but from what I have seen, the OCR results at least didn't get worse for decent scans.

If somebody (a) either has a bad scan for me to test with or (b) can test it for themselves, some feedback would be great!

**Comment by Flameeyes** [comment]
If there is any help I can lend with unpaper please don't hesitate to tag me :)

**Comment by danielquinn** [comment]
@Flameeyes as @pitkley suggested, you could post a link to a low-quality scan you'd like to see work, or even try out his fork and test some stuff yourself :-)

**Comment by Flameeyes** [comment]
Sorry I should have been more clearer, I meant that as a current unpaper
maintainer :)

Although I'd be happy to try this out once I have some spare time!

On Wed, Feb 17, 2016 at 8:36 AM Daniel Quinn <notifications@github.com>
wrote:

> @Flameeyes <https://github.com/Flameeyes> as @pitkley
> <https://github.com/pitkley> suggested, you could post a link to a
> low-quality scan you'd like to see work, or even try out his fork and test
> some stuff yourself :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielquinn/paperless/issues/20#issuecomment-185094551>
> .
>
-- 
Diego Elio Pettenò (aka Flameeyes)

**Comment by Cyber1000** [comment]
Will there be a PR for paperless with unpaper or are there any problems with it right now?

**Comment by danielquinn** [comment]
I see that @pitkley has a [branch](https://github.com/pitkley/paperless/tree/feature/unpaper) where he's started the unpaper integration, but it's fallen out of sync with master for now.  My priority right now is the UI, but when that's ready, I'll be looking at this issue -- that is if @pitkley hasn't already submitted a PR.

**Comment by pitkley** [comment]
@Cyber1000 I have opened PR #74 which adds `unpaper` if you want to test it.

**Comment by danielquinn** [comment]
I've merged @pitkley's unpaper integration PR, so I'm going to go ahead and close this.

**Comment by Cyber1000** [comment]
Thanks, I'll take a look at it.
