### ISSUE TITLE
Updating correspondent and tags of a document via REST API

### ISSUE THREAD

**Issue by thomasbrueggemann** [danielquinn/paperless#200]
I just noticed that updating the correspondent and the tags of a document via the REST API has no effect.

I first tried this in the paperless-desktop API call and then discovered that it also does not have any effect when I go to http://paperless-on-localhost/api/documents/{id} and then manually change the correspondent id to another valid correspondent id in the Content form on the bottom of the page and submit.

Same goes for changing or adding tags.
I changed for example:

```javascript 
{
    "id": 93,
    "correspondent": "http://localhost:9876/api/correspondents/31/",
    "title": "Geschäftsbedingungen",
    "content": "...",
    "file_type": "pdf",
    "tags": [
        "http://localhost:9876/api/tags/1/"
    ],
    "checksum": "161d1456d888784c44b7b8db18396f4a",
    "created": "2017-02-28T16:57:43Z",
    "modified": "2017-03-20T01:23:10.918611Z",
    "file_name": "20170228165743-universitat-kassel-geschaftsbedingungen.pdf",
    "download_url": "/fetch/doc/93",
    "thumbnail_url": "/fetch/thumb/93"
}
``` 

to

```javascript
{
    "id": 93,
    "correspondent": "http://localhost:9876/api/correspondents/31/",
    "title": "Geschäftsbedingungen",
    "content": "...",
    "file_type": "pdf",
    "tags": [
        "http://localhost:9876/api/tags/1/",
        "http://localhost:9876/api/tags/5/"
    ],
    "checksum": "161d1456d888784c44b7b8db18396f4a",
    "created": "2017-02-28T16:57:43Z",
    "modified": "2017-03-20T01:23:10.918611Z",
    "file_name": "20170228165743-universitat-kassel-geschaftsbedingungen.pdf",
    "download_url": "/fetch/doc/93",
    "thumbnail_url": "/fetch/thumb/93"
}
``` 

So I added another tag with the id "5", which exists in the system and the response of the PUT request is the original document with only the tag with the id "1". 

Did I miss something?

**Comment by danielquinn** [comment]
It's very strange.  I look at the code, and I'm using `UpdateModelMixin` and yet the browseable API doesn't show a PUT or DELETE option.  This may very well be broken, so I'll have a look and let you know what I find.

Unfortunately I've got a day job, so I won't be able to look at it immediately, but likely this week.

**Comment by thomasbrueggemann** [comment]
> Unfortunately I've got a day job, so I won't be able to look at it immediately, but likely this week.

I know that problem very well ;-) No worries!

**Comment by danielquinn** [comment]
Ok I've found & fixed the problem.  It turns out that I didn't declare the serialisers for `correspondent` and `tags` properly.  Details are in #202 if you're interested :-)

Also, while you're doing your own development, I'd suggest that you spend some time with the browseable API if you haven't already.  It makes it easy to see what's possible and debug your requests & the responses.  Just go to `http://localhost:8000/api/` and click around :-)

**Comment by thomasbrueggemann** [comment]
Thanks a lot!
And I am frequently checking back on the browsable API, that's super handy! :-)
