### ISSUE TITLE
Space requirement for paperless setup

### ISSUE THREAD

**Issue by d4rken** [danielquinn/paperless#201]
How much space does paperless itself need?

It probably needs space for stuff like:
* Databases
* Metadata
* Thumbnails
* Caches
* etc.

I'm planning to put Paperless into it's own VM. The documents would be stored externally via network share. How much space should I give the Paperless VM?

I'm hoping someone who has been using Paperless for some time could share their experience.

**Comment by danielquinn** [comment]
Well I'm the primary developer, so it's safe to say I've been running it the longest, but I don't know if my car is typical.  The documents are largely addressed to me, and I have stuff in there from immigration authorities and tax departments etc. over almost two years:

* Document store: 278MB
* Virtual environment: 75MB
* Database: 3.7MB
* Total number of documents: 272 (mostly PDFs)

So for the most part, Paperless isn't the problem for disk space, it's the documents themselves.

**Comment by danielquinn** [comment]
Correction: the documents themselves are only 163MB and the thumbnails are 116MB.  I'm posting this on mobile so ssh-ing into my box is kind of a pain in the ass.

**Comment by d4rken** [comment]
Thanks a lot for the quick response. 
I'll probably have a lot more pdfs, or maybe a lot less pdfs depending on how much work it is to split up collections. Kinda planning to take old file folders and dump them whole into an autofeed scanner. Then either have one PDF with the file folder label, or take the time and split the scanned pages up and tag them with the file folder name + document type (bills, taxes, income, insurrance etc).

Assuming this doesn't scale weirdly I should be fine with a 32GB VM disk though 👍.

Still have to find a fitting scanner though (color, duplex, autofeed, if possible networked). Price wise the S1300i looks nice, though no network support... has good ratings though.
