### ISSUE TITLE
Removing all tags

### ISSUE THREAD

**Issue by schinkelg** [danielquinn/paperless#204]
I made a mistake when adding a tag and the retagger added the tag to most of my documents. Can I mass delete all applied tags? All tags I have were automatically added so I can just re-run the retagger.

**Comment by danielquinn** [comment]
Well there's no easy utility to do that, but you should just be able to do it in the Python shell:

```python
# Open the Django shell:
./manage.py shell_plus

# Loop over all documents and remove all associated tags:
for d in Document.objects.all():
    d.tags.clear()
```

Or if you prefer an easy one-liner:

```bash
echo 'for d in Document.objects.all(): d.tags.clear()' | ./manage.py shell_plus
```

Either of these will keep your tags in the system but remove all document associations with any tags.

**Comment by schinkelg** [comment]
Thanks! This workaround solves the issue for me.
