### ISSUE TITLE
IndexError: list index out of range in _get_parser_class

### ISSUE THREAD

**Issue by schinkelg** [danielquinn/paperless#206]
Everything was running fine for days until I got this error:

File "<snip>paperless/src/documents/consumer.py", line 167, in _get_parser_class
    options, key=lambda _: _["weight"], reverse=True)[0]["parser"]
IndexError: list index out of range

For reference: it appears that the line
result = parser(doc)
returns False for all parsers.

**Comment by danielquinn** [comment]
I'm willing to bet that the file in question has an all-caps suffix, like `.PDF` or something, right?  Your issue got me digging and I think I've found [the problem](https://github.com/danielquinn/paperless/blob/master/src/paperless_tesseract/signals.py#L17).

Basically, when the consumer starts it collects a list of available consumers and then for every file, tries to figure out which consumer to use based on a `.test()` method attached to that consumer.  In this case, the default consumer is using a regex on the file name to determine whether it can handle it (`True`) or not (`False`).  Currently, I'm not accounting for file names with capital letters in the suffix.

I'm writing a patch for that now, so if that's your problem, it'll be fixed soon.  If not though, let me know and we'll do some more digging.

**Comment by danielquinn** [comment]
Alright, fix applied, along with a few tests.  Do a `git pull` and restart your consumer and you should be good to go.

**Comment by schinkelg** [comment]
Yep, extension pdf in all caps indeed. Thank you so much! Fix confirmed.
