### ISSUE TITLE
[Bug] consumer does not use right date

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#210]
I am currently consuming some pdf files which has a syntax of the following e.g.
20170329192943Z-Esstisch.pdf
20161002145449Z-arzt-charly.pdf

But the consumer does not use the date information to set the right creation time of the document.

**Comment by Ulli2k** [comment]
Any hints what I did wrong?

**Comment by danielquinn** [comment]
Sorry, I've been busy preparing for [DjangoCon](https://2017.djangocon.eu/) this past week and now I'm en route there so I haven't had much time to debug this for you.  As far as I can tell, those file names look fine, so it may very well be a bug.

If you'd like to try and find the solution yourself while I'm unavailable, just run the test suite with `pytest` and then add your file names to `TestFieldPermutations` in [this file](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py).  Write a test for your specific file names and see what happens.

At the moment, that's the best I can do for you.  Let me know how it pans out, and I'll try to look into this when I return from the conference.

**Comment by danielquinn** [comment]
Ok I know it's been a while, but I got around to this one today and can confirm that while the unit tests pass, the consumer is still not acknowledging the date in the file name.  It's probably a misstep in the consumer itself (rather than the file name parser) so I'll have to look into that when I have more time.

**Comment by danielquinn** [comment]
Ok I figured it out after far too much tinkering... I should have seen this sooner.  The format for the file name is `date - title.extension` not `date-title.extension` as you have here.  Put in a space before and after your dash in your file names above and you should be good to go.
