### ISSUE TITLE
Optional Bulk scanner suggestion in readme.md

### ISSUE THREAD

**Issue by eonist** [danielquinn/paperless#211]
20page cap:
http://www.brother.ca/en-CA/Scanners/11/ProductDetail/ADS1500W?ProductDetail=productdetail

50 page cap:
https://www.amazon.com/Fujitsu-PA03656-B005-Image-Scanner-ScanSnap/dp/B00ATZ9QMO/ref=sr_1_2?s=electronics&ie=UTF8&qid=1491488042&sr=1-2&keywords=Fujitsu+PA03656-B005+Image+Scanner+ScanSnap+iX500

Just a thought. Ignore it if you wish.  ¯\_(ツ)_/¯

**Comment by danielquinn** [comment]
Thanks for the recommendation!  I added a link to the product page on the Fujitsu site, but it may be a good idea in the future to compile a list of scanners people have recommended just to give new users an idea where to start.  For now, though, I'll leave it with just the two we've got.

**Comment by eonist** [comment]
I found it here: http://lifehacker.com/5993869/five-best-document-scanners-for-going-paperless

The one i proposed had a lot of stars on amazon and a lot of feedback.

**Comment by eonist** [comment]
You have my permission to refer to my github user name in the readme. or leave it another user... at your discretion of course.

**Comment by danielquinn** [comment]
I don't generally like to link to things like Amazon pages or Lifehacker articles because these things are necessarily subjective, while the product page for the device in question is as simple as it gets.

As for including your name, I think it might be a fun thing to do use the Github wiki for recommendations or something, but as I've never used it, I'll have to find time to figure it out before I open it up.

**Comment by eonist** [comment]
A product page is subjective? I guess it's the most subjective out of the 3 mentioned sadly. Wiki's are awesome. They can even be managed locally via git. I manage a handful or so via Atom.io 🖖

**Comment by danielquinn** [comment]
I've just added a page to the documentation with [scanner recommendations](https://paperless.readthedocs.io/en/latest/scanners.html) including the one you've mentioned here, and there's a link to your Github user in there as well.

**Comment by eonist** [comment]
Sweet
