### ISSUE TITLE
ProgrammingError at /api/logs/ using MySQL

### ISSUE THREAD

**Issue by philippeowagner** [danielquinn/paperless#213]
getting  the following error 

```
    (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL 
    server version for the right syntax to use near 'SEPARATOR '\n') AS `messages`, 
    MAX(`documents_log`.`modified`) AS `time` FROM `do' at line 1")
```

Could provide more info/versions upon request.

**Comment by danielquinn** [comment]
I don't generally develop against MySQL so I've never seen this come up.  If you can give the the steps to reproduce, I can take a look at what's going on.

**Comment by philippeowagner** [comment]
I checked the MySQL syntax using an [online syntax checker](https://www.piliapp.com/mysql-syntax-check/) first. This works for me using `mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3`. I do not expect issues with other MySQL versions.
