### ISSUE TITLE
Use relative path instead of absolute path in manifest.json

### ISSUE THREAD

**Issue by CkuT** [danielquinn/paperless#216]
Hey !

In order to move my paperless instance from my computer to my server, I dumped all my documents in a local directory. The importer/exporter scripts are amazing, but I had to change the `manifest.json` file to replace the absolute hardcoded paths with the new server paths. 

Is it possible to rely on a relative path for the manifest file ?

**Comment by danielquinn** [comment]
Oooh, yeah that would make a lot of sense.  I'll super busy right now though, so I can't do it.  However, if you send in a pull request, I'll review & merge it :-)

**Comment by CkuT** [comment]
Closed in 22c8049bed87a6dce851dc37c242fc80eeb2aa7b
