### ISSUE TITLE
Question: Does paperless use the text that is stored in the pdf already in addition to OCR?

### ISSUE THREAD

**Issue by githubbrowser** [danielquinn/paperless#225]
Quick question:

A lot of scanners nowadays use their own OCR solutions to detect text in scanned documents.

Does paperless benefit from that? Or does it do its own OCR regardless of what is stored in the existing pdf?

Thanks! :)

**Comment by danielquinn** [comment]
Unfortunately, Paperless is not *currently* smart enough to pull text out of PDFs that already have a text layer.  I think this might be able to be done with pdftk or something, but I don't know for sure.  If you have ideas, or fancy writing some code, a pull request would not go amiss!

**Comment by githubbrowser** [comment]
Thanks! I just had a quick look before I posted the question and it seems like there is a range of more or less messy approaches to the problem. So yes, definitely something to keep in mind.

I'm not an active paperless user yet, though I have been playing with the idea for quite a while. One of these days...

**Comment by danielquinn** [comment]
Alright, well I'll close this issue for now (marking it as `question`) but if you find yourself hacking something together, feel free to send me a pull request :-)
