### ISSUE TITLE
Cryptic tesseract error when OCR'ing PDF file

### ISSUE THREAD

**Issue by jmgilman** [danielquinn/paperless#234]
**Running commit:** 02e0543a022ab9a02aa792a5ea00bd83592c6b52
**OS:** Docker with customized Debian install
**Document being processed:** http://unec.edu.az/application/uploads/2014/12/pdf-sample.pdf

**Please see the error output at the bottom**

I've narrowed it down to not being the processed file itself, as multiple types of files fail with the same error. I'm currently in the process of packaging this app to be deployed with [Cloudron](https://cloudron.io/). The only difference between the Docker setup in the repository and this one is that the file system is set to read-only with the exception of an `/app/data` directory and `/tmp`. Taking away the read-only option and running the container **does not** reproduce the error.

Thus, I've narrowed it down to likely a file write permission. However, I do see that the script is successfully creating temporary files in `/tmp`. The following files exist in `/tmp/paperless/paperless2fq10pbb`:

`convert-0000.png  convert-0000.pnm  convert-0000.unpaper.pnm`

Which leaves the question: what else does tesseract try to write to? It might help if the error were more helpful, but I've yet to correlate the **-9** found in the error output with any actual meaning. 

Any suggestions?

```
19:42:53 [main] Parsers available: RasterisedDocumentParser
19:42:53 [main] Consuming /app/data/paperless/consume/pdf-sample.pdf
19:42:58 [main] Processing sheet #1: /tmp/paperless/paperless2fq10pbb/convert-0000.pnm -> /tmp/paperless/paperless2fq10pbb/convert-0000.unpaper.pnm
19:43:03 [main] [image2 @ 0x21fd4c0] Encoder did not produce proper pts, making some up.
19:43:03 [main] OCRing the document
19:43:03 [main] Parsing for eng
19:43:07 [main] multiprocessing.pool.RemoteTraceback:
19:43:07 [main] """
19:43:07 [main] Traceback (most recent call last):
19:43:07 [main]   File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
19:43:07 [main]     result = (True, func(*args, **kwds))
19:43:07 [main]   File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
19:43:07 [main]     return list(map(*args))
19:43:07 [main]   File "/app/code/paperless/src/paperless_tesseract/parsers.py", line 214, in image_to_string
19:43:07 [main]     return ocr.image_to_string(f, lang=lang)
19:43:07 [main]   File "/usr/local/lib/python3.5/dist-packages/pyocr/tesseract.py", line 358, in image_to_string
19:43:07 [main]     raise TesseractError(status, errors)
19:43:07 [main] pyocr.error.TesseractError: (-9, b'Tesseract Open Source OCR Engine v3.04.01 with Leptonica\n')
19:43:07 [main] """
19:43:07 [main]
19:43:07 [main] The above exception was the direct cause of the following exception:
19:43:07 [main]
19:43:07 [main] Traceback (most recent call last):
19:43:07 [main]   File "/app/code/paperless/src/manage.py", line 18, in <module>
19:43:07 [main]     execute_from_command_line(sys.argv)
19:43:07 [main]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
19:43:07 [main]     utility.execute()
19:43:07 [main]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 359, in execute
19:43:07 [main]     self.fetch_command(subcommand).run_from_argv(self.argv)
19:43:07 [main]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 294, in run_from_argv
19:43:07 [main]     self.execute(*args, **cmd_options)
19:43:07 [main]   File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 345, in execute
19:43:07 [main]     output = self.handle(*args, **options)
19:43:07 [main]   File "/app/code/paperless/src/documents/management/commands/document_consumer.py", line 57, in handle
19:43:07 [main]     self.loop()
19:43:07 [main]   File "/app/code/paperless/src/documents/management/commands/document_consumer.py", line 67, in loop
19:43:07 [main]     self.file_consumer.consume()
19:43:07 [main]   File "/app/code/paperless/src/documents/consumer.py", line 124, in consume
19:43:07 [main]     parsed_document.get_text(),
19:43:07 [main]   File "/app/code/paperless/src/paperless_tesseract/parsers.py", line 55, in get_text
19:43:07 [main]     return self._get_ocr(images)
19:43:07 [main]   File "/app/code/paperless/src/paperless_tesseract/parsers.py", line 114, in _get_ocr
19:43:07 [main]     raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE)
19:43:07 [main]   File "/app/code/paperless/src/paperless_tesseract/parsers.py", line 163, in _ocr
19:43:07 [main]     r = pool.map(image_to_string, itertools.product(imgs, [lang]))
19:43:07 [main]   File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
19:43:07 [main]     return self._map_async(func, iterable, mapstar, chunksize).get()
19:43:07 [main]   File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
19:43:07 [main]     raise self._value
19:43:07 [main] pyocr.error.TesseractError: (-9, b'Tesseract Open Source OCR Engine v3.04.01 with Leptonica\n')
```

**Comment by jmgilman** [comment]
So after some more reverse engineering, I need a little help connecting the dots here:

* The document is consumed into the queue
* It's converted to pnm
* It's run through unpaper which produces a .unpaper.pnm
* What happens next?

 It looks like the final `.unpaper.pnm` file is located in the temp directory. Eventually, `_ocr` is called in `paperless_tesseract/parsers.py`. If I follow, the image file being passed is the `.unpaper.pnm` file created earlier. 

`_ocr` passes it off to `image_to_string` which then attempts opening an image file in the `RasterisedDocumentParser.SCRATCH` directory. That setting for my setup in my `paperless.conf` as:

```
PAPERLESS_CONVERT_TMPDIR="/app/data/paperless/tmp"
```

However, after the parser crashes, I don't have any files in that directory on the affected system. 

Furthermore, eventually `image_to_string` is called in `pyocr/tesseract.py` which then attempts saving the passed image file into a temporary directory prefixed by *tess_*, however I also don't have any such folders in my `/tmp` directory. 

So, I'm guessing Tesseract is failing because it's not actually getting an image passed. However, it's not clear in which of the snippets above that the file is failing. If I had to take a guess, I'd say that perhaps my `PAPERLESS_CONVERT_TMPDIR` setting is not being respected?

**Comment by jmgilman** [comment]
Issue ended up being a memory issue which caused a SIGTERM to be sent to the Tesseract process. Fixed by increasing memory on the container.

**Comment by danielquinn** [comment]
Interesting.  Sorry I wasn't able to respond to you sooner, but I'm in the UK so all of these messages came through when I wasn't around.

I'm curious, what was the memory limit before & after your container change, and how big was the file being OCR'd?  I don't have any numbers regarding memory requirements for Tesseract on different files, so I'm curious what caused it.

**Comment by jmgilman** [comment]
That's fine, this was actually one of three bugs on the issue (also raised one on Cloudron and pycor). 

The memory limit before was 256MB and I increased it to 1024MB. The actual file size was only 8KB. The issue was that by sheer luck running `tesseract` via the command line **did not** push the memory limit, however running it through Python's `subprocess` module **did** push it. It ended up giving a lot of false indications unfortunately.
