### ISSUE TITLE
POST consumption endpoint?

### ISSUE THREAD

**Issue by jmgilman** [danielquinn/paperless#236]
Following the documentation, I'm sending a POST request to the document root of my Paperless URL (http://my.paperless.com/) with the appropriate fields, but I'm getting a CSRF token error:

```
<p>CSRF verification failed. Request aborted.</p>
            <p>You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>
            <p>If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for &#39;same-origin&#39; requests.</p>
```

Is this the wrong endpoint? I wouldn't of expected a CSRF authentication since I thought that was the point of the `signature` field.

Code snippet for reference:

```
import requests

url = 'http://my.paperless.com/'
data = {
    'correspondent': 'blah',
    'title': 'My Document',
    'signature': '123abc'
}

files = {'document': open('pdf-sample.pdf', 'rb')}
r = requests.post(url, data=data, files=files)
r.text # Shows the aforementioned error
```

**Comment by jmgilman** [comment]
Code snippet for reference:

```
import requests

url = 'http://my.paperless.com/'
data = {
    'correspondent': 'blah',
    'title': 'My Document',
    'signature': '123abc'
}

files = {'document': open('pdf-sample.pdf', 'rb')}
r = requests.post(url, data=data, files=files)
r.text # Shows the aforementioned error
```

**Comment by jmgilman** [comment]
After some digging around in the source, the only thing that hints at document upload is the `/push` endpoint. So, naturally, I tried POSTing to it, but I'm getting a 500 error:

```
Environment:


Request Method: GET
Request URL: http://localhost:8000/push

Django Version: 1.10.5
Python Version: 3.5.2
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'documents.apps.DocumentsConfig',
 'reminders.apps.RemindersConfig',
 'paperless_tesseract.apps.PaperlessTesseractConfig',
 'flat_responsive',
 'django.contrib.admin',
 'rest_framework',
 'crispy_forms',
 'django_filters']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py" in get
  174.         return self.render_to_response(self.get_context_data())

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py" in get_context_data
  93.             kwargs['form'] = self.get_form()

File "/usr/local/lib/python3.5/dist-packages/django/views/generic/edit.py" in get_form
  45.         return form_class(**self.get_form_kwargs())

Exception Type: TypeError at /push
Exception Value: 'NoneType' object is not callable
```

**Comment by danielquinn** [comment]
I don't generally use the POST interface, so I'm afraid I'll need some time to debug this.  There are a few others using this though, so perhaps they'll chime in before I get to it.

**Comment by jmgilman** [comment]
No worries, I'd love to troubleshoot it myself but unfortunately I have very limited experience with Django, so the stack trace above isn't exactly clear to me. All I was able to figure out was it's likely something with the `PushView` somehow not having a valid form set.

**Comment by jmgilman** [comment]
Was anyone else able to reproduce this error?

**Comment by danielquinn** [comment]
Ok so first of all thank you for finding this and for taking the time to help me find out what was wrong.  There were a number of problems here, all of which *should* be solved in #237:

1. The documentation was either ambiguous or just flat-out missing information:
    * It didn't give you the name of the field for the uploaded file
    * It didn't give you the URL to POST to.  It's no wonder you had a hard time.
2. The code was most definitely broken.  It's funny, because I've had people talk to me on here like they've been using the POST method, but having seen the code, I don't believe it.  There were at least two show-stopper bugs in there that would have prevented it from working at all even if someone could have magically found their way around the documentation.

For now, the new PR I just issued should fix both of these problems and make it a lot easier for new users to try it out.  Please, if you have some time, try out that code before I merge it just so I have a second pair of eyes on it.  I'd like to merge it into `master` tomorrow some time, so if you can't try it out before then, don't worry, it'll be in master soon.

**Comment by jmgilman** [comment]
So I've tested the revisions and they work, however there is one caveat I wanted to address: it looks like you're still requiring that `PAPERLESS_SHARED_SECRET` to be defined before the `push` url pattern is added ([see here](https://github.com/danielquinn/paperless/blob/master/src/paperless/urls.py#L43)). The problem is that the shared secret is no longer being used to authenticate the POST request since you've moved to using Basic Auth. This is likely going to greatly confuse someone who doesn't initially define that setting and attempts to POST as it will return a 404 on them. 

I think this line simply needs to be removed?

**Comment by danielquinn** [comment]
You're absolutely right @jmgilman.  I'll re-open this as a reminder to remove it.  If you've got some time though, I'm happy to merge a PR.

**Comment by danielquinn** [comment]
Alright I've finally gotten around to patching this.  Thanks for you help in tracking all this down :-)

You can `git pull` on `master` or just check out the [latest release](https://github.com/danielquinn/paperless/releases/tag/0.6.0).
