### ISSUE TITLE
LDAP auth backend

### ISSUE THREAD

**Issue by nebulade** [danielquinn/paperless#239]
Hi, I am trying to use `django_auth_ldap` for the [Cloudron](https://cloudron.io) paperless [package](https://git.cloudron.io/cloudron/paperless-app) and after adding the relevant config fields to the settings.py and adding `django_auth_ldap.backend.LDAPBackend` to `AUTHENTICATION_BACKENDS` I can see a successful ldap bind on the server and the logs in paperless also look promising:
```
[23/Jun/2017 12:46:54] "GET /admin/login/?next=/ HTTP/1.1" 200 1829
search_s('ou=users,dc=cloudron', 2, '(username=%(user)s)') returned 1 objects: cn=uid-7fe53bfb-6f54-42a5-a8e2-f618e76b1a81, ou=users, dc=cloudron
Populating Django user nebulon
[23/Jun/2017 12:46:58] "POST /admin/login/?next=/ HTTP/1.1" 200 1992
[23/Jun/2017 12:47:03] "GET / HTTP/1.1" 302 0
[23/Jun/2017 12:47:10] "GET /admin/login/?next=/ HTTP/1.1" 200 1829
``` 
However I keep on getting redirected to the login page. I do not have much knowledge how things are tied up in django, so possibly I am just missing one piece?

I tried adding some debug logging to https://github.com/danielquinn/paperless/blob/fa4924d5ba804cb79f4cee30c0460d155fb59fa6/src/paperless/mixins.py already but it does not even seem to get hit.

Any ideas or pointers would be great.

**Comment by danielquinn** [comment]
Wow, I have no idea how [django-auth-ldap](https://pythonhosted.org/django-auth-ldap/) works as I've never used it, but it sounds like the problem is in how it's passing the authenticated nature of the session to the rest of Django.  Typically with these things, you [override AUTHENTICATION_BACKENDS](https://pythonhosted.org/django-auth-ldap/install.html) with the module in question and then Django *Just Works*™️.  I can't think of any case where Paperless' code is even coming into play.

I'm going to tag @jmgilman on this one since I think he's the one responsible for Cloudron port.  Maybe he has more insight than I do.

**Comment by nebulade** [comment]
Yes I also pinged him outside github, he packaged the app itself and it is actually already working very well, we just didn't publish it to the library yet as it would be great to have the "single sign-on" aspect with Cloudron there from the start. Looks like more in depth knowledge of django is required ;-)

**Comment by danielquinn** [comment]
Well I'm afraid I just don't know enough about LDAP or Cloudron to really help here, but if you guys wanna spin up an instance, point me to it, and give me a shell, I'd be happy to log in and fiddle around with vim to see if I can figure things out.

**Comment by nebulade** [comment]
Thanks a lot for that offer to help. Please either ping me at https://chat.cloudron.io  or send me a mail (address should be in my github profile) and I can help you to get started if you have time.

**Comment by nebulade** [comment]
For anyone interested in this, I have managed to make LDAP work. It only requires changes to the `settings.py` to use ldap as user source and further configure the django ldap plugin.

An example file, in this case for the Cloudron app, can be viewed at https://git.cloudron.io/cloudron/paperless-app/blob/4ed7622084b9ded18d2403f7655773a4f94b6469/settings.template.py 

Since this is only a configuration topic, I think this is out of scope to be solved within this project, so I will close the issue. Maybe it could be added to the docs at some point.

**Comment by danielquinn** [comment]
Hi @nebulade I'm sorry I never got around to helping out with the LDAP stuff.  My life got super-busy.  However, if you'd like to issue a PR for the documentation to include LDAP support, I'd be happy to merge it.
