### ISSUE TITLE
Automated document processing

### ISSUE THREAD

**Issue by kskyten** [danielquinn/paperless#243]
Thanks for the great project!

I'm hacking together an automated document processing script and I need some help with it.
Currently I have a latex template with a QR code in it. This page will be scanned first to provide the metadata. Now, there's two ways to transfer this metadata to paperless:
- change the filename in the pre-consumption script
- modify the database in the post-consumption script

The first method will probably work for now, but might be a bit fragile and is hard to extend. Could you give some pointers on how to go about implementing the second method? I'm not very familiar with Django.

**Comment by MasterofJOKers** [comment]
Did you think about using [HTTP POST consumption](https://github.com/danielquinn/paperless/blob/master/docs/consumption.rst#http-post) and providing the metadata within the request instead?

**Comment by kskyten** [comment]
Thanks! Somehow I missed that in the documentation. That does seem like a better way of doing it.
