### ISSUE TITLE
wrong time/ timezone

### ISSUE THREAD

**Issue by brightdroid** [danielquinn/paperless#249]
The web-ui shows me "Note: You are 2 hours ahead of server time." when editing reminders.
Indeed, it also saves in UTC rather than my timezone which may be ok but it should show me my local time.

I tried to add `/etc/localtime:/etc/localtime:ro` and `/etc/timezone:/etc/timezone:ro` as volumes and adding `TZ=Europe/Berlin` to docker-compose.env but it still shows not my local time.

**Comment by ddddavidmartin** [comment]
I don't know how the docker setup works, but in any case did you set the [`PAPERLESS_TIME_ZONE` value in the paperless config](https://github.com/danielquinn/paperless/blob/master/paperless.conf.example#L162)?

**Comment by brightdroid** [comment]
Thanks I had to add this to my `docker-compose.env`
```
PAPERLESS_TIME_ZONE=Europe/Berlin
```
