### ISSUE TITLE
Don't delete files after document_consume

### ISSUE THREAD

**Issue by goldsz** [danielquinn/paperless#252]
I would like to make it so that paperless won't delete documents in the PAPERLESS_CONSUMPTION_DIR. I would like to point that directory at the location to my document storage where I send all new important documents, scans etc. That way all documents would be ingested into paperless without any copying around.

My first thought was that after the consumer finished processing file FILENAME we could touch a FILENAME.paperless file in the directory to flag not to process it again.

**Comment by MasterofJOKers** [comment]
How about putting the important files into one directory and have some sort of output directory for files already processed by paperless? Would that work for you, too? It's moving around, though.

Could you elaborate on the purpose of "not copying around"? Size restrictions? Manual interaction? What's the problem with "copying around" that annoys you? This information might help in finding an appropriate solution.

Another idea might be extended attributes instead of additional files or a list of already consumed files. Both won't clutter the directory of important files so much.

**Comment by goldsz** [comment]
So, our current process is any important documents we just put onto a network file share. Everyone is good about putting docs there. Our document scanner FTPs documents there. This share is backed up, offsite storage etc. 

I would like to point paperless at this location  have it index the documents and provide its nice OCR / web interface to find what we are looking for.

**Comment by danielquinn** [comment]
Well Paperless is smart enough to not re-import a document that's already been imported, but there's two problems to consider:

1. Paperless still expects to be placing a copy of the document into its media directory so it can be served up by the webserver.
2. The process of deciding whether or not it should import a document requires the hashing of the entire file and caching that value in memory.  This would mean that as your document collection grows, starting the consumer will take longer and longer (as it'll loop over all of the files, reading, hashing, and ignoring until it finds a file it hasn't consumed yet) and the memory footprint will grow as the library grows.

If (1) isn't a big deal, then adding a flag to not delete the source file is easy enough, assuming the drawbacks of (2) aren't going to make the consumer painful for your use case.

**Comment by goldsz** [comment]
FYI,
  I've been running for about a year now with the following hack:
* I rsync periodically from the NFS to a local directory on paperless's server.
* I hacked out the consumer deleting the local file

This allows me to keep a pristine read only version on the NFS (no bugs can accidentally delete our source documents). 

However, I have some custom hacks and 3 copies of every document.
