### ISSUE TITLE
Bad Request on document upload via REST

### ISSUE THREAD

**Issue by Schlangguru** [danielquinn/paperless#258]
Hi, I currently try to implement an android application to upload documents that are scanned with the smartphone camera. And I'm really struggling with the `/push` API Endpoint. It gives me always a `400 - Bad Request` Response.  
I'm not a python developer and have no experience with Django. Could you give me a hint on how to activate a proper Logging for the REST API so I can trace down this issue?

**Comment by MasterofJOKers** [comment]
The view seems to respond with "Bad request" if the form could not be validated. Did you look into the response body? It might contain the actual error information.

**Comment by Schlangguru** [comment]
You're right. The ErrorResponse Body says "That title is suspicious". It seems that the upload can't handle files with "(" or ")" in it's name. The document title is "New Document(1).pdf"
Thanks for the hint. Now I'm a bit closer to my goal.

**Comment by ddddavidmartin** [comment]
Have a look at the docs as they mention what is allowed :)
http://paperless.readthedocs.io/en/latest/consumption.html#http-post

>  Note that there are restrictions on what characters you can use here. Specifically, alphanumeric characters, -, ,, ., and ‘ are ok, everything else is out. You also can’t use the sequence ` - ` (space, dash, space).

**Comment by Schlangguru** [comment]
Missed that. Sometimes reading the docs is a good idea ;)
