### ISSUE TITLE
No parsers could be found

### ISSUE THREAD

**Issue by OmgImAlexis** [danielquinn/paperless#259]
I've looked all through the docs as well as Github issues and I can't find anything related to this issue.

I'm using paperless in a docker container. I've added a single file called `Scan.jpeg` to test paperless but I can't seem to get it to do anything at all with the file.

```
root@730c011090b8:/usr/src/paperless/src# ./manage.py document_consumer
Starting document consumer at /consume
Parsers available: 
No parsers could be found for /consume/Scan.jpeg
Parsers available: 
No parsers could be found for /consume/._Scan.jpeg
```

**Comment by danielquinn** [comment]
Nice find!  Thanks for the report.  I've just patched `paperless_tesseract/signals.py` to match for `jpe?g` now, so `.jpeg` files should work.  If that's not the case though, just re-open this and I'll try again :-)
