### ISSUE TITLE
Is consumer supposed to keep running?

### ISSUE THREAD

**Issue by mannp** [danielquinn/paperless#261]
I am trying to start the docker so I can docker exec inside to set it up?

Should it run and keep running or just run once?

I don't have access to docker compose on unraid, so cannot run the setup command without the docker continuing to run.

Thanks

**Comment by mannp** [comment]
> I have started the docker with no external directories as I am having ownership issues.
> 
> That said with all the directories internal in the docker, I still get errors in changing the group of something? ' '?
> 
> I understood from the manual that things should run without the /export directory, so why is the docker trying to change permissions of a non existent directory?
> 
> Any help would be appreciated.
> 
> Thanks.
> 
> chgrp: cannot access ‘’: No such file or directory
> Changing group of export directory:
> 
> failed.
> 
> Either try to set it on your host-mounted directory
> directly, or make sure that the directory has o+x
> permissions and the files in it at least o+r.
> chmod: cannot access ‘’: No such file or directory
> Changing group permissions of export directory:
> 
> failed.
> 
> Either try to set it on your host-mounted directory
> directly, or make sure that the directory has o+x
> permissions and the files in it at least o+r.
> 
> Type 'manage.py help ' for help on a specific subcommand.
> 
> Available subcommands:
> 
> [auth]
> changepassword
> createsuperuser
> 
> [django]
> 
> compilemessages
> createcachetable

**Comment by Strubbl** [comment]
Consumer shall run when you want the new documents to be processed and included in paperless. I keep it running. So i have two instances with different parameters of the same docker container: one for the web server and one for the consumer.

**Comment by mannp** [comment]
Thanks for that.

The web server part keeps running fine, but the default docker build seems to just run and list the command line options and then exits.

I was rather hoping it just continued to run while waiting for those command to be given.

As it just lists the command line parameters I am unable to initialise the consumer docker.

**Comment by Strubbl** [comment]
here are my docker commands for creating both instances

```
docker create --name paperless_web -p 8000:8000 -v /data/paperless/data:/usr/src/paperless/data -v /data/paperless/media:/usr/src/paperless/media -e PAPERLESS_PASSPHRASE=555NOSE strubbl_paperless runserver 0.0.0.0:8000

docker create --name paperless_consumer -v /data/paperless/data:/usr/src/paperless/data -v /data/paperless/media:/usr/src/paperless/media -v /data/paperless/consume:/consume -v /data/paperless/export:/export -e PAPERLESS_PASSPHRASE=555NOSE strubbl_paperless document_consumer
```

this way both containers run with `docker start` command until i stop them with `docker stop`

**Comment by mannp** [comment]
Hey thanks very much for those, I have made a note and will try using them tomorrow :)

**Comment by danielquinn** [comment]
It looks like this issue has been ironed out (Thanks @Strubbl!) so I'm closing it.  Feel free to re-open if you need to.
