### ISSUE TITLE
suggestion: good printer scanner with direct ftp support

### ISSUE THREAD

**Issue by ayounggun** [danielquinn/paperless#265]
Hi all

The brother MFC-J6930DW works very well as a scanner. Its £189 inc tax in the UK (~ $250).

- two sided scanning
- auto document feeder
- a3 flat bed
- scan to ftp server *directly from the printer*.

The last point is great because you don't have to have an intermediate piece of software running on a laptop or desktop. This means you can open post, put it in the scanner's feeder, and press a button and it will scan everything straight to paperless for processing. You don't need to boot up another machine beforehand.

Downsides are its physically quite big. It's an inkjet, but this isn't a massive issue as I hardly print anything anyway, so the running cost is minimal regardless.

ScanSnap iX500 doesn't support direct ftp to scanning as far as I can see. You need the software running to somewhere else as a middleman to send the files to ftp. I tried the ADS-1600W and it jammed often.

Apologies for putting this in an issue I wasn't sure where was best, but wanted to share for others. Couldn't find a forum. 

Thanks

**Comment by lenucksi** [comment]
There are a lot of other network scanners that scan directly to a configured FTP. It would indeed be good to have proper support for them.
However as far as I understood paperless you basically just make the scanner scan to some directory and have paperless index the result? Would that be correct? And how does one do that correctly?

**Comment by ayounggun** [comment]
Hi sorry I probably should not have added this as an issue :). I wanted to recommend a relatively cheap direct to ftp scanner somewhere for the project. I thought other users might find it later when looking through the repo on github. please delete as necessary!

**Comment by asmagill** [comment]
FWIW in my admittedly limited searching, finding a relatively cheap scanner that supports scanning directly to a network server that uses an open protocol (e.g. ftp, smb, dav, etc.) isn't trivial -- you usually have to dig into the docs a bit to find out if the marketing blurb "scan directly over the network to your computer/server" uses an open protocol or proprietary one.  

I know that paperless is focused on pulling files from a directory, and is unconcerned with how the files got there, but for the user trying to build an automated document storage system, such a list would be useful, in my opinion, even if it's kept to just "someone made it work with model X" and no further details about how, etc. since that would understandably be beyond the scope of the project.

**Comment by ayounggun** [comment]
I got quite frustrated trying to separate those that used intermediary
software from those that were direct to network (ftp smb etc). As you say
its not always that clear until you drill down into the specs.

What was the one that you used? I an thinking about setting my parents up
as they struggle with paperwork as they get older.

**Comment by ayounggun** [comment]
Although the readme does suggest ADS-1500W and ScanSnap iX500 which I know
works for many

**Comment by asmagill** [comment]
I actually haven't bought one yet... I'm still in the process of migrating my parents documents which are stored with Neat.  (a) the Mac has always had poor support from them, (b) I don't do subscription plans, and (c) especially not on someone else's cloud. Luckily the files can be saved as PDFs, so this project was a no brainer; I haven't quite got to the point of using it for my own stuff yet, so I haven't actually purchased a scanner... still looking.

**Comment by danielquinn** [comment]
Ok after all this discussion, I've added a [scanner recommendations](https://paperless.readthedocs.io/en/latest/scanners.html) page to the documentation.  Feel free to issue a pull request if you have anything you'd like to add or change :-)
