### ISSUE TITLE
AttributeError: __exit__ when using document_consumer

### ISSUE THREAD

**Issue by schollz** [danielquinn/paperless#27]
Very cool tool! I ran into the following bug when I ran (using Ubuntu 14):

```bash
$ ./manage.py document_consumer
Consuming /home/phi/Dropbox/Scans/New Doc 1_1.pdf
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/phi/Downloads/paperless/src/documents/management/commands/document_consumer.py", line 68, in handle
    self.loop()
  File "/home/phi/Downloads/paperless/src/documents/management/commands/document_consumer.py", line 98, in loop
    text = self._get_ocr(pngs)
  File "/home/phi/Downloads/paperless/src/documents/management/commands/document_consumer.py", line 159, in _get_ocr
    raw_text = self._ocr(pngs, self.DEFAULT_OCR_LANGUAGE)
  File "/home/phi/Downloads/paperless/src/documents/management/commands/document_consumer.py", line 201, in _ocr
    with Image.open(os.path.join(self.SCRATCH, png)) as f:
AttributeError: __exit__
```

What fixed the issue for me is getting rid of the `with Image.open` statement on [these lines](https://github.com/danielquinn/paperless/blob/0ec63ae1f99f765811cf530057fa7dc3d7287769/src/documents/management/commands/document_consumer.py#L199-L201) to:
```python
            f = Image.open(os.path.join(self.SCRATCH, png))
            self._render("    {}".format(f.filename), 3)
            r += self.OCR.image_to_string(f, lang=lang)
```

I didn't want to submit a pull request since it seems like no one else had this issue. Otherwise everything is great, thank!!

**Comment by pitkley** [comment]
This error indicates that your version of the Python Imaging Library (PIL) does not support `Image` to be used as a context manager. It seems like this was introduced back at least in [version 2.5.0 of Pillow](https://github.com/python-pillow/Pillow/commit/196a48b4fd5cd388d5412d7aa0115e99b6e8c792), the PIL fork Paperless is using.

Can you verify which version you have currently installed? You can do this by e.g. executing `pip show Pillow` within your (virtual) environment, which should output something along the following lines:

    $ pip show Pillow
    ---
    Metadata-Version: 1.1
    Name: Pillow
    Version: 3.0.0
    Summary: Python Imaging Library (Fork)
    Home-page: http://python-pillow.github.io/
    Author: Alex Clark (Fork Author)
    Author-email: aclark@aclark.net
    License: Standard PIL License
    Location: /usr/local/lib/python3.5/site-packages
    Requires:

**Comment by schollz** [comment]
Yeah, seems right. My version is 2.3.0:

```bash
$ pip3 show Pillow
---
Name: Pillow
Version: 2.3.0
Location: /usr/lib/python3/dist-packages
Requires:
```

Thanks! I'll upgrade PIL.

**Comment by pitkley** [comment]
Usually it's best to install your requirements via `pip(3) install -r requirements.txt` in the directory you cloned Paperless to. It specifies all requirements and the versions they should be.

If this fixed your issue, be sure to close it :+1:

**Comment by danielquinn** [comment]
You should also make sure that you're running Python3 and not Python2:

```bash
$ python --version
Python 3.4.3
```

I wrote this thing for Python3 only and I'm not testing for Python2 so I can't guarantee that it'll work with the wrong version.

**Comment by schollz** [comment]
Yep, I've got it working now, thanks!!
