### ISSUE TITLE
GCE driver: __init__() missing 1 required positional argument: 'secure'

### ISSUE THREAD

**Issue by skjbulcher** [danielquinn/paperless#276]
I'm using:

- libcloud 2.2.1 / 2.2.0
- python 3.5.2
- virtualenv
- GCE service account with a json credential file

Python code looks like this:

    from libcloud.compute.types import Provider
    from libcloud.compute.providers import get_driver

    def run():
        """ Run this script
        """
        ComputeEngine = get_driver(Provider.GCE)
        driver = ComputeEngine(user_id='****@****.com',
                               credential_file='serviceaccount.json',
                               project='****')

    run()

When I run my code, I'm getting:

    Traceback (most recent call last):
      File "./myscript.py", line 47, in <module>
        run()
      File "./myscript.py", line 21, in run
        project='ebs-it', secure=True)
      File "/***/virtualenv/lib/python3.5/site-packages/libcloud/compute/drivers/gce.py", line 1795, in __init__
        super(GCENodeDriver, self).__init__(user_id, key, **kwargs)
      File "/***/virtualenv/lib/python3.5/site-packages/libcloud/common/base.py", line 975, in __init__
        self.connection = self.connectionCls(*args, **conn_kwargs)
    TypeError: __init__() missing 1 required positional argument: 'secure'

This looks [perfectly textbook](http://libcloud.readthedocs.io/en/latest/compute/drivers/gce.html) to me.  I created a [stackstorm question here](https://stackoverflow.com/questions/47877954/libcloud-missing-1-required-positional-argument-error-during-driver-init), but the more I look into it the more it looks like a bug. E.g., if I don't specify `user_id`  and `credential_file`, libcloud asks me to load a URL and type a code; since I'm using a service account, I shouldn't need to do  this (I think).

**Comment by Strubbl** [comment]
Did you file this issue into the wrong project? I cannot see any relation with paperless

**Comment by skjbulcher** [comment]
You're right. I must have clicked on the wrong 'issues' button while I was viewing apache/libcloud.
