### ISSUE TITLE
[REQ] Disable login

### ISSUE THREAD

**Issue by kmlucy** [danielquinn/paperless#279]
I use nginx's auth-request module for single sign on, and I was hoping to use it with Paperless as well. In order to do so, I would need to disable the login screen. Is this currently possible? Or could an option be added?

**Comment by danielquinn** [comment]
Unfortunately, not easily.  Paperless uses Django's built-in admin which, as an *admin* requires a logged-in user to operate.  There may be a work-around though.  If you add [django-basicauth](https://pypi.python.org/pypi/django-basicauth) to the `MIDDLEWARE` setting (and configure it to alingn with a user you have in Paperless), that might be a way to allow Django to treat a BasicAuth-authenticated user as a Paperless-logged-in user.

Go ahead and give that a try, and if it works out, maybe we can figure out a way to make this more user-friendly.

**Comment by kmlucy** [comment]
I've played with it a bit, but honestly I think it is beyond my capabilities.

**Comment by danielquinn** [comment]
Alright then, I'll label this as `enhancement` and look into it when I have some time.

**Comment by mtonnie** [comment]
I Döner know tue auth-request module from nginx but I have used Remote_User backend / middleware. It just requires come configuration and a variable with tue username after authentication.

In case a username is provided in an variable sou should take at [Django's remote user description](https://docs.djangoproject.com/en/1.11/howto/auth-remote-user/).

**Comment by kmlucy** [comment]
Resolved by https://github.com/danielquinn/paperless/pull/295
