### ISSUE TITLE
Port 80 fails

### ISSUE THREAD

**Issue by chris-aeviator** [danielquinn/paperless#282]
when using port 80 the webserver service errors out with:

```
me@my-server /opt/paperless $ docker-compose run webserver 
Error: You don't have permission to access that port.
```

**Comment by danielquinn** [comment]
That's not a bug, it's a UNIX standard.  On UNIX-based systems, non-privileged users can only assign services to ports above `1024`.  If you want to put paperless on port 80 you must either:

1. Install and run Nginx as a proxy forward to Paperless running locally on an unprivileged port.
2. Run Paperless as root.  *Don't do this*.  Paperless wasn't designed to run on a public server and by default has debugging turned on.  I can't imaging the field day anyone with a decent black hat background would have with your server running Paperless as root.

**Comment by danielquinn** [comment]
Have a look at [Making things a little more permanent](https://paperless.readthedocs.io/en/latest/setup.html#using-a-real-webserver).  This should get you where want to be.
