### ISSUE TITLE
documents overview

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#286]
long time ago I changed the document overview back to the list view instead of having the thumbnails.
But after an update today the same procedure does not longer work
	sudo nano documents/templatetags/hacks.py
		path = "admin/documents/document/change_list_results.html" <-- remove following line

does anybody have an idea to get the listview back?

**Comment by ncl2fth** [comment]
I just got paperless working and am also interested in the list view...

**Comment by danielquinn** [comment]
The files that handle the look & feel in this case are:

* `src/documents/templates/admin/documents/document/change_list.html`
* `src/documents/templates/admin/documents/document/change_list_results.html`

Strictly speaking, I think you could probably just *delete one or both of these files* to get back the list view.  Either that, or tweak these to get what you like.  I hope this helps?

**Comment by Ulli2k** [comment]
I have done an paperless update and the workaround with deleting "change_list_results.html" does not longer work to get the list view back.
Could you help me to get rid of the thumbnails?

**Comment by danielquinn** [comment]
We're doing a lot of *weird* stuff in the admin templates, so the best option for you is probably to nuke that whole directory:

```bash
rm -r src/documents/templates/admin/
```

I hope that helps.
