### ISSUE TITLE
Automatic detection of document type

### ISSUE THREAD

**Issue by BastianPoe** [danielquinn/paperless#292]
Hi!

I have many documents that I want to store digitally and have found that searching for documents in the pile is a lot easier when knowing the type (e.g. invoice, credit card statement, etc.) of the stored documents. Since a couple of days I am thinking about an automated way to determine the type of a document (or even better the subject of it).

Currently, I do see the following options:
* use tags
* add a separate field for this (similar to correspondent)
* find a magic library / webservice 

What do you think? What are your needs?

Bastian

**Comment by danielquinn** [comment]
Depending on what you want to use to determine the type of a document, the tags system may be all you need.  Typically I use a regex or even a literal match on my tags and that's served me well so far.  Documents that contain the term `NHS` are automatically tagged `health`, while anything from `HMRC` it tagged `taxes` etc.

Do you have a different need/idea?

**Comment by danielquinn** [comment]
Closing this one to try to clean up the queue a bit.  If you have some ideas you'd like to try out, feel free to re-open.
