### ISSUE TITLE
Reset admin password

### ISSUE THREAD

**Issue by rajil** [danielquinn/paperless#297]
Hello,

Is there a way to reset the admin password of the Webserver? 

I tried the following,
```
 # /home/paperless/paperless/src/manage.py shell
Python 3.6.4 (default, Dec 21 2017, 01:11:04) 
[GCC 4.2.1 Compatible FreeBSD Clang 4.0.0 (tags/RELEASE_400/final 297347)] on freebsd11
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> User.objects.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'User' is not defined
```

**Comment by mtonnie** [comment]
Usually you should be able to use django's default features which already offer a way to [change the password](https://docs.djangoproject.com/en/1.11/ref/django-admin/#django-admin-changepassword) when you are able to access the shell.
Here is also an [alternative way](https://docs.djangoproject.com/en/1.11/topics/auth/default/#changing-passwords), but same prerquisite.

**Comment by rajil** [comment]
I had to create a superuser first using `/home/paperless/paperless/src/manage.py createsuperuser` first. Afterwards, i was able to login.

Not sure why this happened, as I had a perfectly working Paperless before.
