### ISSUE TITLE
OCR broken

### ISSUE THREAD

**Issue by rajil** [danielquinn/paperless#298]
The OCR was working previously. But after some updates it is broken. The log shows,

```
  As FORGIVING_OCR is enabled, we're going to make the best with what we have.
  Language detection failed!
  Language detection error: No features in text.
  Parsing for eng
  OCRing the document
  Consuming /usr/home/vftp/scandump/Report_002706.pdf
```

I have following packages installed,

```
tesseract-3.05.01_3            Commercial quality open source OCR engine
tesseract-data-3.04.00         Trained language data for the Tesseract OCR engine

# ls -la /usr/local/share/tessdata/eng.traineddata
-r-xr-xr-x  1 root  wheel  21876550 Feb 25  2017 /usr/local/share/tessdata/eng.traineddata

```

**Comment by danielquinn** [comment]
That's a warning message, rather than an error and it appears when the language-guessing library can't figure out what language the document is in.  This guess is managed by pulling the middle page (if your PDF is multi-page) out of the doc, OCRing it for English and then passing whatever text it finds to a language-guessing library which should return a 3-letter language code.

If that library can't figure out what language it is, we fallback to the default action, which is to assume the doc is in English and just go for it.

In your case, it looks like everything went fine.  My guess is that the page it picked probably didn't have enough text to form a reasonable guess, so it just fell back to English and consumed the document anyway.

Given that the last line of your output says that it did in fact consume the document, I'm going to assume that there's no bug here?  Did the file appear in Paperless after a few minutes?  If not, just re-open this issue and if you can provide the entire log so I can figure out what's going on.

**Comment by mogllee** [comment]
The document does get consumed, but the thumbnail doesnt show the OCR. The document was full of English language text.

How do i get the full log?

**Comment by rajil** [comment]
The document does get consumed, but the thumbnail doesnt show the OCR. The document was full of English language text.

How do i get the full log?

**Comment by danielquinn** [comment]
Logging is all available in the web interface at `/admin/documents/log/`  If the consumer said it, it'll be in there.  Hope that helps :-)

**Comment by rajil** [comment]
Here is a log of a document i scanned,
![image](https://user-images.githubusercontent.com/379266/36643008-dfc1fd6a-1a0b-11e8-95ee-2e64af634004.png)

The document doesnt show any thumbnail. Any idea what could be broken?

**Comment by danielquinn** [comment]
That's only a portion of the log, and unfortunately, none of it mentions anything about the thumbnail.  Am I correct in assuming you're using the Docker installation method?  I think your best bet in this case would be to do one or all of these things:

1. Look at the output of the webserver container when you load the page that *should* have the thumbnail on it.  When the server tries to send you the file, there should be some sort of output explaining why it's not working.
2. Take a look at the debugging tools in your browser to make sure that the file isn't being blocked by an extension or something.  In Firefox, you can access these tools by going up to the menu and accessing `Web Developer » Web Console` and reloading the page.  `Ctrl+Shift+K` will also do the trick.
3. Look at the logs of the consumer process to get the full output of what's going on as the file is consumed.  There might be some output there that could help.

Assuming you're using the Docker installation method, you should be able to view the logs of a container with `docker-compose logs webserver` and `docker-compose logs consumer` respectively.

Let me know what you find!

**Comment by rajil** [comment]
I am running this in a FreeBSD jail. I dont have any other webserver running.
```
# ps aux
USER        PID %CPU %MEM    VSZ    RSS TT  STAT STARTED     TIME COMMAND
paperless  4933  5.6  0.1 298752  91364  -  SJ   Sat10   95:46.61 /usr/local/bin/python3 /home/paperless/paperless/src/manage.py runserver 172.16.1.39:8000 (python3.6)
root       4477  0.0  0.0  10492   2056  -  SsJ  Sat10    0:00.43 /usr/sbin/syslogd -s
root       4487  0.0  0.0  26596   4560  -  IsJ  Sat10    0:01.74 pure-ftpd (SERVER) (pure-ftpd)
root       4523  0.0  0.0  10468   1652  -  IsJ  Sat10    0:00.00 daemon: /home/paperless/paperless/src/manage.py[4524] (daemon)
paperless  4524  0.0  0.1 309224 128092  -  SJ   Sat10    0:10.00 python3 /home/paperless/paperless/src/manage.py document_consumer (python3.6)
root       4531  0.0  0.0  10468   1656  -  IsJ  Sat10    0:00.00 daemon: /home/paperless/paperless/src/manage.py[4532] (daemon)
paperless  4532  0.0  0.0 223816  50752  -  IJ   Sat10    0:04.44 python3 /home/paperless/paperless/src/manage.py runserver 192.168.1.2:8000 (python3.6)
root       4555  0.0  0.0  20628   5152  -  SsJ  Sat10    0:01.44 sendmail: accepting connections (sendmail)
smmsp      4558  0.0  0.0  20628   4848  -  IsJ  Sat10    0:00.03 sendmail: Queue runner@00:30:00 for /var/spool/clientmqueue (sendmail)
root       4562  0.0  0.0  12592   2068  -  SsJ  Sat10    0:00.70 /usr/sbin/cron -s
root      43217  0.0  0.0  43764   2384  4  IJ   14:43    0:00.03 login [pam] (login)
root      43227  0.0  0.0  21708   3812  4  SJ   14:43    0:00.08 -csh (csh)
root      46197  0.0  0.0  21208   2188  4  R+J  14:47    0:00.01 ps aux
```

**Comment by danielquinn** [comment]
Both the consumer and webserver log to stdout, and do so based on a log level set by the environment variable `PAPERLESS_CONSUMER_LOG_LEVEL`.  What I would suggest is the following:

1. Set `PAPERLESS_CONSUMER_LOG_LEVEL=DEBUG` in `/etc/paperless.conf`.
2. Start the consumer and set it to direct all of its out put to a log file: `python3 manage.py document_consumer >& /path/to/consumer.log`
3. Do the same for the webserver.

Hopefully somewhere in all of that are some details regarding what's happening.

**Comment by rajil** [comment]
I redirected the output of consumer and webserver.
 
```
# cat /usr/local/etc/rc.d/paperless-consumer 
#!/bin/sh

. /etc/rc.subr

name="paperlessconsumer"
rcvar=paperlessconsumer_enable

paperlessconsumer_user="paperless"
pidfile="/var/run/${name}.pid"


command="/home/paperless/paperless/src/manage.py document_consumer 2>&1|tee /tmp/consumer.log "
start_cmd="/usr/sbin/daemon -f -p $pidfile -u $paperlessconsumer_user $command"

load_rc_config $name
run_rc_command "$1"
```
and
```
# cat /usr/local/etc/rc.d/paperless-webserver 
#!/bin/sh

. /etc/rc.subr

name="paperlesswebserver"
rcvar=paperlesswebserver_enable

paperlesswebserver_user="paperless"
command_interpreter="/usr/local/bin/python3"

command="/home/paperless/paperless/src/manage.py runserver 172.16.1.39:8000 2>&1 |tee /tmp/webserver.log"
pidfile="/var/run/${name}.pid"

start_cmd="/usr/sbin/daemon -f -p $pidfile  -u $paperlesswebserver_user $command"


load_rc_config $name
run_rc_command "$1"

```
Unfortunately, the logs were empty.

```
# cat /tmp/webserver.log 
/usr/local/etc/rc.d/paperless-webserver: WARNING: $command_interpreter runserver != python3
87337

# cat /tmp/consumer.log 
/usr/local/etc/rc.d/paperless-consumer: WARNING: $command_interpreter document_consumer != python3
87325
```

**Comment by danielquinn** [comment]
Well that's not a Paperless error.  It looks like there's something amis in how you're starting the service.

For starters let's eliminate any extraneous moving parts and just exectue paperless on the command line.  No starter script, no jail.  Just:

1. Create a virtualenv `virtualenv --python python3 .virtualenv
2. Activate the virtualenv: `. .virtualenv/bin/activate`
3. Install the dependencies: `pip install requirements.txt`
4. Run `./manage.py document_consumer`
5. Watch the output and see what's going on.

Once you have that working, you can go about trying to write a custom startup script and/or run it in a jail.

**Comment by rajil** [comment]
I have a setup a virtualenv as you suggested. I scanned a document which produced a valid pdf (can open in okular), but this what i got

```
(.virtualenv) $ ./manage.py document_consumer
Starting document consumer at /usr/home/vftp/scandump
Parsers available: RasterisedDocumentParser
Consuming /usr/home/vftp/scandump/Report_002768.pdf
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.

   **** This file had errors that were repaired or ignored.
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.
   **** Error reading a content stream. The page may be incomplete.
   **** File did not complete the page properly and may be damaged.

   **** This file had errors that were repaired or ignored.
   **** Please notify the author of the software that produced this
   **** file that it does not conform to Adobe's published PDF
   **** specification.

Processing sheet: /tmp/paperless/paperless-ao7hmz39/convert-0001.pnm -> /tmp/paperless/paperless-ao7hmz39/convert-0001.unpaper.pnm
Processing sheet: /tmp/paperless/paperless-ao7hmz39/convert-0000.pnm -> /tmp/paperless/paperless-ao7hmz39/convert-0000.unpaper.pnm
OCRing the document
Parsing for eng
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/pyocr/tesseract.py", line 214, in detect_orientation
    angle = int(output.get('Rotate', output['Orientation in degrees']))
KeyError: 'Orientation in degrees'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/home/paperless/paperless/src/paperless_tesseract/parsers.py", line 286, in image_to_string
    orientation = ocr.detect_orientation(f, lang=lang)
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/pyocr/tesseract.py", line 224, in detect_orientation
    % (ex.message, original_output))
AttributeError: 'KeyError' object has no attribute 'message'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/home/paperless/.virtualenv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/home/paperless/paperless/src/documents/management/commands/document_consumer.py", line 57, in handle
    self.loop()
  File "/usr/home/paperless/paperless/src/documents/management/commands/document_consumer.py", line 67, in loop
    self.file_consumer.consume()
  File "/usr/home/paperless/paperless/src/documents/consumer.py", line 123, in consume
    date = parsed_document.get_date()
  File "/usr/home/paperless/paperless/src/paperless_tesseract/parsers.py", line 209, in get_date
    text = self.get_text()
  File "/usr/home/paperless/paperless/src/paperless_tesseract/parsers.py", line 80, in get_text
    self._text = self._get_ocr(images)
  File "/usr/home/paperless/paperless/src/paperless_tesseract/parsers.py", line 140, in _get_ocr
    raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE)
  File "/usr/home/paperless/paperless/src/paperless_tesseract/parsers.py", line 189, in _ocr
    r = pool.map(image_to_string, itertools.product(imgs, [lang]))
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
AttributeError: 'KeyError' object has no attribute 'message'
```

**Comment by danielquinn** [comment]
That's *really* odd.  I've never seen anything like that before.  That error message is coming from `convert`, part of ImageMagick and has nothing to do with Paperless.  However, the failure of `convert` to produce anything of value is breaking everything all the way down after that.

Stuff to check:

* Permissions: as you're running in a BSD jail, is it possible that Paperless is calling `convert` and that it can't read the file in question?  What if you run `convert --scale 500x500 --alpha remove /path/to/original.pdf /tmp/convert-%04d.png` as the user running Paperless?
* The file itself.  If the scanner is producing the file, can it be opened by other software?

Outside of the above, I'm tapped for ideas.

**Comment by rajil** [comment]
I was able to resolve this and have a working paperless in a FreeBSD jail. The issue was that FreeBSD upstream packages are built using print/ghostscript9-agpl while we need print/ghostscript9-base. To make this change one needs to self compile packages using poudriere. I had to specify in /usr/local/etc/poudriere.d/make.conf the following:
`DEFAULT_VERSIONS+=ghostscript=9`

The following packages needs to be installed in the jail(compiled using poudriere).
```
# pkg query -e "%#d > 0 && %#r = 0" "%o"
graphics/ImageMagick7-nox11
shells/bash
security/gnupg
graphics/poppler
ftp/pure-ftpd
databases/py-sqlite3
lang/python3
graphics/tesseract
```

**Comment by danielquinn** [comment]
Holy crap, that's a lot of work to go through just to get Paperless working.  Thanks for your thorough explanation!  Did you want to write a snippet for the [troubleshooting section of the documentation]()?  I can always copy/paste what you've done here, but if you want the credit, it's all yours :-)
