### ISSUE TITLE
Feature request: Text context in search results

### ISSUE THREAD

**Issue by jat255** [danielquinn/paperless#30]
Another useful feature might be having a column in the data table that shows up when you do a search, and shows a little bit of context from the text contents on the front page (so you know which file to download). This would be useful particularly if your documents don't have particularly descriptive titles.

**Comment by danielquinn** [comment]
This is tough for a few reasons:

1. Currently, we're working with the Django admin, and interface "sugar" is difficult there.
2. The quality of the OCR'd data isn't very high. and I currently strip extra spacing to make searching easier.  I'm not sure that displaying this stuff is really all that useful.

**Comment by danielquinn** [comment]
I think I'm going to close this one, since i can't figure out how to improve the data quality.  If at some point someone comes along with a slick way to get the OCR'd text to look nice, then this would make more sense.

**Comment by neeklamy** [comment]
As for reason 2, OCR, this is probably no help, but have you seen [PdfMasher](https://github.com/pylam/pdfmasher)? It takes a different approach to OCR, more of a hands on solution. I haven’t tried it out so I can’t comment on how well it works.

Perhaps it could be an option for more complicated documents.
