### ISSUE TITLE
Importing some documents can cause document_consumer to crash and leave bogus data in the database

### ISSUE THREAD

**Issue by matthewmoto** [danielquinn/paperless#303]
I found this accidentally (scanning a tax document), but it caused the underlying call to _convert_ to fail and not generate the thumbnail image.  This wasn't picked up by the RasterizedDocumentParser and it crashed document_consumer trying to open the non-existent thumbnail file.

It also left a document entry in the database with a broken thumbnail link.

To fix, you just need to check the exit status of this command (and any other shell-outs) and fail gracefully.

To reproduce, you can make set PAPERLESS_CONVERT_BINARY=/bin/false to simulate the failure.

**Comment by danielquinn** [comment]
Ew, yeah that's an ugly one to find.  Thanks for reporting it.  Was there something wrong with the document that we should check for in advance of running these commands or was this a freak thing where it'd be uncommon to happen, but good to account for?

**Comment by matthewmoto** [comment]
I think it's safe to treat it like an edge case here. It was an ugly
document that has the first page long and the second page a different size
(my duplex ADF scanner borked things for some reason).

Normally, I'd just share the file, but it's a tax form chock full of PII
and financial data.

If I ever reproduce it with something less sensitive, I'll definitely
share, but the error looks like it's down in ghostscript under convert
anyway so we can likely just pass the buck upstream.

**Comment by danielquinn** [comment]
Ok, this should be fixed in `master` now, though I'm waiting on a few other issues to be resolved before I release another version.  Thanks for the report!
