### ISSUE TITLE
Strange quality issues when downloading the 'original'

### ISSUE THREAD

**Issue by skuzzle** [danielquinn/paperless#310]
Hi,

from my initial understanding I thought paperless would store the original files as is, so that I would get the exact same file that I imported when downloading it from paperless. But while inspecting some original PDF files I found that the 'very orignal' and the file downloaded from paperless differ greatly in quality. Is there some setting to store the very original unprocessed file?

**Comment by danielquinn** [comment]
I guess it depends on how you're downloading it from Paperless.

There's literally nothing done to the original before it's encrypted, so if you're downloading it from the admin, you should be getting a byte-for-byte copy of the original as all the UI does is decrypt what it finds locally.

If you're noticing a quality degredation, I'm guessing that you're not looking at the PDF, but rather the thumbnail?  If that's not the case, I'll need a more detailed explanation of what you're doing to reproduce this.

**Comment by skuzzle** [comment]
Please never mind. I have been viewing the files in different viewers: the downloaded one directly in chrome and the original in SumatraPDF. The displaying in chrome is considerably worse than in SumatraPDF.

**Comment by danielquinn** [comment]
No problem :-)  Thanks for updating the ticket!
