### ISSUE TITLE
Ansible playbook

### ISSUE THREAD

**Issue by ovv** [danielquinn/paperless#318]
More a shameless plug than an actual issue. I made an ansible role for paperless a while ago and got to clean it up this week. I figured it could be useful to share it here.

[ansible-role-paperless](https://github.com/ovv/ansible-role-paperless)

**Comment by danielquinn** [comment]
Neat!  I was thinking of adding a "Related Projects" section to the Paperless readme and would include @thomasbrueggemann's [paperless-desktop](https://github.com/thomasbrueggemann/paperless-desktop) and this.  That sound good to you?

**Comment by ovv** [comment]
Awesome !

**Comment by danielquinn** [comment]
Cool beans.  What say you, @thomasbrueggemann?  You cool with me promoting Paperless-Desktop in the README?

**Comment by thomasbrueggemann** [comment]
@danielquinn For sure, thanks! It's still very beta'ish, but maybe I can acquire some collaborators this way ☺️

**Comment by danielquinn** [comment]
Alright, I've added both of your projects to the README :-D
