### ISSUE TITLE
New imported documents list

### ISSUE THREAD

**Issue by ovv** [danielquinn/paperless#319]
Following #302 the date matching is working way better for my docs thanks. 

I usually check that the scanned document is of good quality before recycling/archiving the originals, now that the dates are matched it became harder to find them. I think providing a list of recent imports and/or a way to order documents by import date would be useful to check the quality of recent documents.

**Comment by ddddavidmartin** [comment]
Agreed. I think the list of Recent Actions on the start page may be a good spot to mention newly imported documents. 

I was actually considering adding an option to disable the automatic date matching for this reason. It seemed easier to implement. I tend to update the title and tags by hand for new documents anyway so changing the date does not add much effort. Or, less effort than trying to get to the document as it is.

**Comment by ovv** [comment]
The `Recent Actions` seems like a good fit. As far as I know it's a standard part of the django admin so I'm not sure if we can easily add new actions from the `document_consumer`

**Comment by danielquinn** [comment]
It looks like the `Recent Actions` section is handled as part of [Django's `LogEntry` model](https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#logentry-objects).  Adding some code to the consumer to create a LogEntry object might be all that's necessary if one of you wanna try it.

**Comment by ddddavidmartin** [comment]
Thanks for the pointer @danielquinn! I'm pretty busy at the moment and I won't be able to contribute more than a bit of armchair commenting, so feel free to give it a go @ovv. I'm happy to try out any proposed changes though.

**Comment by ovv** [comment]
Not really sure when I can take a look at it but I'll drop a comment when / if I start. In the meantime if anyone want to give it a shit, that's ok with me.

**Comment by CkuT** [comment]
I quickly gave a shot for this :
https://github.com/danielquinn/paperless/commit/45e18d709406e9631c5406d5c718c5ef43de1351

It is just a new signal handler on `document_consumption_finished` that creates a LogEntry object.

https://i.imgur.com/dyTMqZo.png

I'm open to improvements about some little things :
- LogEntry wants a `User` for creating the object. I currently take the first user of the database, but maybe we could create a specific "consumer" user ?
- I use the `document.created` as the `LogEntry.action_time`, but I think `document.modified` would be better. What do you think ?

**Comment by ddddavidmartin** [comment]
Hi @CkuT, nice! Would you be able to open a pull request with your changes? Then they are easy to try out just by checking out the pull request branch. Thanks!

**Comment by ovv** [comment]
Looks good.
Just a small question about `document.created` is that the importation date or the one discovered by the date matching algorithm ?
IMO it should be the importation date, in case it's not maybe we could replace it by a `datetime.datetime.now()`

**Comment by CkuT** [comment]
Yep, `document.created` is the one discovered by the date matching algorithm (or taken in the filename : https://paperless.readthedocs.io/en/latest/guesswork.html#file-naming)

You are right, the `datetime.datetime.now()` (or `document.modified`) would clearly be better !

**Comment by danielquinn** [comment]
I've just merged @CkuT's work on this one so I'll close this now.  Thanks to all of you for coordinating this new feature :-)

**Comment by ovv** [comment]
Awesome thanks @CkuT

**Comment by ddddavidmartin** [comment]
Nice work @CkuT, this is great!
