### ISSUE TITLE
document_retagger equivalent for Correspondents

### ISSUE THREAD

**Issue by GarethFox** [danielquinn/paperless#347]
Hi,

I am trying to understand if it is more profitable to attach the entity source of a processed document to a correspondent or a tag rule.
This is why I am now wondering if there is, or could have a `sudo docker-compose run --rm consumer document_retagger` (when using docker image) equivalent to reload and repatch documents with new correspondents rules ?

Many thanks,

**Comment by danielquinn** [comment]
If I understand your question, I think you're looking for `manager.py document_correspondents`.  It should assign your correspondents based on the rules you've set.

**Comment by GarethFox** [comment]
Hi @danielquinn ,
I was asking this as I was not able to find it in the ReadThe Docs/Utilities command realted to manager.py.
Thanks a lot, I will test this next week.
