### ISSUE TITLE
Search Tags

### ISSUE THREAD

**Issue by thinkjk** [danielquinn/paperless#354]
Is there a way to include tags in the search?

If I have a document tagged as dog, and search for dog nothing shows up.

Thank you.

**Comment by danielquinn** [comment]
Great idea, and it was the easiest thing to do on my list all day, so thank you for that!  I've updated `master` so give it a try and if it doesn't work as you'd expect, feel free to re-open this issue.  Also, congratulations on your first Github issue :-) :1st_place_medal:
