### ISSUE TITLE
OCR date read incorrectly

### ISSUE THREAD

**Issue by rajil** [danielquinn/paperless#355]
My documents have the date in format mm/dd/yy, however paperless interprets the date as dd/mm/yy after OCR. Is there a way to fix this?

For example log shows,
`Detected document date 2018-01-05T00:00:00-06:00 based on string 05/01/2018`
and interprets it as 5 January instead of 1st April.

**Comment by danielquinn** [comment]
Not at the moment, no.  That format is a minority in the world (as far as I know, it's unique to the US) so we had to make a call and opted for the more widely adopted format.  Have a look at [this big beautiful regular expression](https://github.com/danielquinn/paperless/blob/master/src/paperless_tesseract/parsers.py#L221) courtesy of @BastianPoe -- that's the beast Paperless is using to detect dates in a document.

As far as I know, to fix this, we'd have to add some sort of configurable option, something like `PAPERLESS_DATE_FORMAT="MM-DD-YYYY"` and then use that value in the `get_date()` method.  Bastion, do you have any idea if this is doable?

**Comment by BastianPoe** [comment]
There is an option for that, see https://github.com/danielquinn/paperless/blob/master/src/paperless/settings.py#L276.

Add the following line to your config file and you should be fine:
PAPERLESS_DATE_ORDER="YMD"

**Comment by BastianPoe** [comment]
Sure, exactly. I have edited my comment above.

**Comment by PowerScrypt** [comment]
@danielquinn I can confirm `PAPERLESS_DATE_ORDER="MDY"` fixed this issue.  Thanks!
