### ISSUE TITLE
Documents API does not return Alphabetical results correctly.

### ISSUE THREAD

**Issue by NickBusey** [danielquinn/paperless#382]
Passing `ordering:name` to `/api/documents` returns an array that is mostly, sorta, kinda alphabetical, but definitely not entirely.

For example, I get a document with title `"title": "scan0005",` returned before `"title": "Receipt.jpg",`

I thought it was just a capitalization issue, but that doesn't appear to be the issue because other capital items are before the `	"title": "scan0005",` result.

I may try and investigate this soon myself, but I wanted to log it and bring it up in case anyone knows the issue offhand.

**Comment by danielquinn** [comment]
Are you sure you meant to say `ordering:name` and not `ordering: title`?  There's no `name` field to order by, so that would definitely present a problem.

Have you tried out the browsable API at /api yet?  That should include a bunch of handy tools to help you compile the URL you want.

**Comment by NickBusey** [comment]
Ah ok, so I switch to `title`, and it's closer now, but still not working entirely. It does seem that now the issues is capitalization. All my capitalized documents show up in alphabetical order first, then after they are done, all the lower case documents are after that, again in alphabetical order. I would expect them to be in one continuously alphabetical list.

**Comment by danielquinn** [comment]
Ah.  Well the good news is that at least things are sorting properly now, though I guess the behaviour isn't the way you expected (sorry).  Truth be told though, that's the correct behaviour, as a capital `Z` has a higher value than a lower case `a`.  We could switch the way `django-filter` does sorting with [this trick](https://stackoverflow.com/questions/31862420/) for a case-insensitive sort, but that would mean losing the case-sensitive sort, which I believe is the expected default.

Sorry, but I think this is the sort of thing that I'm not going to change, but if you want to patch Paperless to sort the way you prefer, now you have the code to do it :-)
