### ISSUE TITLE
Suggestion: Enable document_consumer command to be run from webinterface

### ISSUE THREAD

**Issue by Sblop** [danielquinn/paperless#388]
Hi Daniel,

I love this project and have migrated basically all of our documents to this. So first of a big thanks.

This is not so much an issue, but more as a suggestion:
I only use the CLI interface whenever I need to add docs. Paperless does not parse my docs automatically so after adding enough docs I frequently log into the CLI to run manage.py document_consumer command... Wouldn't it be an idea to add a button in the web interface which sole purpose is to start the consumer? 

/Benjamin

**Comment by denellum** [comment]
I understand why this would be wanted : 
My set up, i scan directly to my consumer directory.
I then go edit the naming convention IN the consumer directory.
Then would like to run the consumer, that way i'd not need either of the following : 
a 2nd location to FTP things to from my scanner, OR have to log in via SSH to run the consumer.

I am working on this, ill have an UGLY version of the code here soon. I am currently testing it now.

**Comment by danielquinn** [comment]
Thanks to @erikarvstedt for poking their head in on this one.  For the record, this isn't something I'm likely to ever add to Paperless as (as @erikarvstedt pointed out) it goes against the primary goal of the project: to limit the required amount of interaction.

I'm going to close this one, but if someone has a terribly compelling reason they think will change my mind, I'm happy to have the discussion.
