### ISSUE TITLE
Screenshot/demo

### ISSUE THREAD

**Issue by The-Compiler** [danielquinn/paperless#4]
I want to try this somewhen soon after looking at the README - but a screenshot or a live demo would really help getting an impression how this looks like :wink:

**Comment by danielquinn** [comment]
That's a good idea, and I'll definitely do something like that... when I consider it to be ready.  As it is, I'm still actively developing it, so I don't want to give the impression that this is 100% ready for prime-time.

In fact, you've inspired me to add a beta notice to the top of the README just so people don't get any big ideas about stability :-)

**Comment by csu** [comment]
:+1: for screenshots

**Comment by strages** [comment]
A little youtube video would do wonders! Guessing if this is useful to me yes or no ;)

Use [ffscreencast](https://github.com/cytopia/ffscreencast) for a painless experience!

**Comment by danielquinn** [comment]
@strages ffscreencast looks like an excellent tool for this.  Can someone post here roughly what they'd hope to see in such a demo?  It's easier to make something if you've got a storyboard to start with.

**Comment by dklesev** [comment]
+1

**Comment by csu** [comment]
@danielquinn I'm just interested in seeing what the UI looks like and how all the different functionalities work before I go through all the effort to install it.

**Comment by strages** [comment]
Exactly, see the following scenario: A room with a lot of backlogging
administration papers. Lets handle this all digitally! Scan everything,
lets see how it looks on the pc.

On Mon, Feb 15, 2016 at 10:51 PM Christopher Su <notifications@github.com>
wrote:

> @danielquinn <https://github.com/danielquinn> I'm just interested in
> seeing what the UI looks like and how all the different functionalities
> work before I go through all the effort to install it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielquinn/paperless/issues/4#issuecomment-184410015>
> .
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>

**Comment by danielquinn** [comment]
Well a demo is a much bigger undertaking, so I've added a screenshot for now.  A demo will have to wait a while though 'cause there's more pressing things to do, but if someone wants to submit one of their own, by all means, post it on YouTube or something and I'll link to it here.

For now though, I'm going to close this in order to keep the issue queue uncomplicated.  If someone *really* feels that a demo is necessary, by all means, open a new issue explicitly asking for that (this one was complicated by asking for both a screenshot and a demo).

**Comment by strages** [comment]
great :) although a better resolution would be nice!

On Tue, Feb 16, 2016 at 10:26 AM Daniel Quinn <notifications@github.com>
wrote:

> Well a demo is a much bigger undertaking, so I've added a screenshot for
> now. A demo will have to wait a while though 'cause there's more pressing
> things to do, but if someone wants to submit one of their own, by all
> means, post it on YouTube or something and I'll link to it here.
>
> For now though, I'm going to close this in order to keep the issue queue
> uncomplicated. If someone *really* feels that a demo is necessary, by all
> means, open a new issue explicitly asking for that (this one was
> complicated by asking for both a screenshot and a demo).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/danielquinn/paperless/issues/4#issuecomment-184594780>
> .
>
-- 
--

*Dimitrie Hoekstra, UI & Interaction Designer*
dhesign.com  | dimitriehoekstra@gmail.com | LinkedIn
<https://www.linkedin.com/in/dimitrieh> | Twitter
<https://twitter.com/strages33/>
