### ISSUE TITLE
How to change Guesswork / Document parser to reflect file names

### ISSUE THREAD

**Issue by massaquah** [danielquinn/paperless#402]
Hi,
I have been trying to make Paperless work for me for a few hours and now all depends on making it work with my document naming convention.

All of my documents are named this way:

[Correspondent][Year]document_title-with-optional-date-YYYYMMDD[optional-family-member]
e.g. :
[Otelo][2016]Rechnung-20160401[Thea]

Which paperless file would I have to change in which way if I wanted the information 

-Correspondent 
-Year for a filter rather then "by Month"
-document title
-tag (name of the subfolder within the consumer directory)

**Comment by danielquinn** [comment]
If I'm understanding you correctly, you have a bunch of files with a very specific naming convention that you'd like to import with Paperless, and you want to know how to make Paperless understand your naming convention.

Sorry, but there's currently no way to do that.  I'd recommend looking into a mass-renaming application to get your files to conform to the conventions Paperless understands.  If however you'd rather dig into the code and *make* Paperless understand, you'll probably want to check out [the FileInfo class](https://github.com/danielquinn/paperless/blob/master/src/documents/models.py#L373-L419) where we've got some rather elaborate regular expressions.  Adding one in there should do the trick for you.
