### ISSUE TITLE
Thumbnails lost after restoring

### ISSUE THREAD

**Issue by rototom** [danielquinn/paperless#409]
I restored a backup and lost all the thumbnails. How can I let them being regenerated?

**Comment by danielquinn** [comment]
Hold old was your backup?  'Cause the export process should have dumped the thumbnails as well as the original documents.

If it's an old backup, or you somehow lost the thumbnails, you could execute this in the Django shell:

```python
for d in Document.objects.all():
    print("convert -scale 500x5000 -alpha remove {}[0] {}".format(d.source_path, d.thumbnail_path))
```

This will output a whole bunch of shell commands that will read the original source file and use it to generate the thumbnail file.

You can access the Django shell by going to the `src` directory and running `./manage.py shell_plus`.

**Comment by danielquinn** [comment]
That's the sort of error you get when you try to execute the shell without your virtualenv being enabled.  Assuming your virtualenv is in `/path/to/paperless/.virtualenv`, you can do this:

```
cd /path/to/paperless
. .virtualenv/bin/activate
cd src
./manage.py shell_plus
```

I hope that helps?
