### ISSUE TITLE
(losslessly) compress thumbnails

### ISSUE THREAD

**Issue by Findus23** [danielquinn/paperless#410]
Hi,

Many thanks for the great software, it really makes it possible for me to keep an overview over my documents.

Since I disabled GPG thumbnails load much faster, but I think there are still some things left to make the list of documents feel really fast.

One thing I noticed is that the website has 35MB for me (96 documents), mostly because of the thumbnails. And while I wouldn't make them lower resolution, they should compress really well as most documents mostly consist of white space.

And indeed even the default settings of `optipng` can reduce the size of the thumbnail files by up to 55%. So I think it would be worth it to (optionally) add a one time cost of compressing the images, so they load faster every time afterwards.

What do you think?

**Comment by danielquinn** [comment]
That sounds really handy actually.  So handy that [I've just added it](https://github.com/danielquinn/paperless/commit/750ab5bf85300db7903bb24e93dbe55f60f02307).  Thanks for the idea!

This change will only affect *future* thumbnails though.  If you want to optimise the ones you currently have (and you aren't using encryption), you can just run optipng on all of the existing thumbnail files manually:

```bash
cd media/documents/thumbnails
for f in *.png; do optipng -o5 ${f}; done
```
