### ISSUE TITLE
AttributeError at /admin/documents/document/ -> templates/admin/base.html, error at line 49

### ISSUE THREAD

**Issue by mannp** [danielquinn/paperless#415]
The previous update caused this error. No changes have been made except consuming more documents.

I occurs when I select to enter the documents area.

http://dpaste.com/1WTQXJ2

Template error:
In template /usr/lib/python3.6/site-packages/django/contrib/admin/templates/admin/base.html, error at line 49
   'NoneType' object has no attribute 'year'
   39 :                 {% if site_url %}
   40 :                     <a href="{{ site_url }}">{% trans 'View site' %}</a> /
   41 :                 {% endif %}
   42 :                 {% if user.is_active and user.is_staff %}
   43 :                     {% url 'django-admindocs-docroot' as docsroot %}
   44 :                     {% if docsroot %}
   45 :                         <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
   46 :                     {% endif %}
   47 :                 {% endif %}
   48 :                 {% if user.has_usable_password %}
   **49 :                 <a href="{% url 'admin: password_change' %}">{%  trans 'Change password' %}</a> /**
   50 :                 {% endif %}
   51 :                 <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
   52 :             {% endblock %}
   53 :         </div>
   54 :         {% endif %}
   55 :         {% endblock %}
   56 :         {% block nav-global %}{% endblock %}
   57 :     </div>
   58 :     
   59 :     {% block breadcrumbs %}

**49 'admin:password_change' trans 'Change password'**

**Comment by pengc99** [comment]
Hi mannp, the way I solved this was by opening the sqlite database and looking for a document with a date that was obviously wrong - in my case it was a document that had a date of 0590 as the year or something like that. Edit that to a more reasonable value, like 2018 and that will fix it. You can then go back into the GUI to edit the date in the document back to whatever you want it to be.

**Comment by mannp** [comment]
Hi @pengc99 I did see your method and have looked in my db, but the dates all look fine.

At first glance I thought your issue was the same as mine, but didn't appear to be the same after some further review.

Did you have this admin password issue too?

**Comment by danielquinn** [comment]
Hi @mannp, here's a few things we can do to try to narrow down the problem.

### Re-enable a login.

The login-related error appears to be happening when users try to change stuff via the admin (add/delete tags for example).  Simply viewing the documents page shouldn't cause a problem in that case.  Regardless, if you enable logins and try to visit the documents page, we'll see if the same error happens.

### Dump out all the dates in your database

This can be done one of two ways, either by using the database shell, or the Django shell:

#### The Database Shell

```bash
echo "SELECT created, modified, added FROM documents_document ORDER BY added" | ./src/manage.py dbshell
```

#### The Django Shell

```bash
echo -e "for d in Document.objects.all():\n    print(d.created, d.modified, d.added)\n\n" | ./src/manage.py shell_plus
```

Alternatively, you can login to the shell and start executing Python stuff:

```bash
./src/manage.py shell_plus
```

---

My guess is that somewhere in there is a date that's broken.  Either it's `NULL` or just *weird*.  If you've got a big database, you can try different `ORDER BY` values to help sift through the noise.

**Comment by mannp** [comment]
Thanks @danielquinn for spelling it out like that, as when all the dates were dumped it was very obvious a date in 2036 was not correct :)

I have now changed them and am back in business, thank you and thank you again @pengc99 

I presume some extra checking on the date is planned, as I have not checked if its already fixed.
