### ISSUE TITLE
AttributeError at /admin/documents/document/

### ISSUE THREAD

**Issue by goose-ws** [danielquinn/paperless#416]
When I pull up my /AttributeError at /admin/documents/document/ I get the following error message:

`Request Method: GET  

http://192.168.1.100:7412/admin/documents/document/  

1.11.13  

AttributeError  

'DocumentAdmin' object has no attribute 'get_changelist_instance'  

/home/goose/bin/paperless/src/documents/admin.py in changelist_view, line 212  
/usr/bin/python3  

3.5.3  

['/home/goose/bin/paperless/src',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/home/goose/.local/lib/python3.5/site-packages',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages']  

Wed, 3 Oct 2018 15:57:10 +0000`

![image](https://user-images.githubusercontent.com/874014/46423259-305d0800-c704-11e8-80bb-c7f6151376ff.png)

Here is the traceback it provides:
http://dpaste.com/3ABY9YA.txt

I checked out issue #414 and #415 -- However, I don't believe it's a dates issue, as I originally had no documents at all and was getting the error. After processing in 3 documents, I see the dates as:

`goose@eddard:~/bin/paperless/src$ echo "SELECT created, modified, added FROM  documents_document ORDER BY added" | ./manage.py dbshell  

2018-01-08 00:00:00|2018-10-03 15:56:34.695460|2018-10-03 15:56:34.695273  

2017-10-01 00:00:00|2018-10-03 15:56:38.391423|2018-10-03 15:56:38.391252  

2018-03-27 20:55:34.355462|2018-10-03 15:56:38.896063|2018-10-03 15:56:38.895864  

goose@eddard:~/bin/paperless/src$`

Would thoroughly appreciate any help :)

---

Edit: Please disregard the 30 revisions on this. I can't get line breaks to work inside the code blocks, sorry.

**Comment by Forceu** [comment]
I have the same problem, the traceback is a followed:

```
Environment:


Request Method: GET
Request URL: http://banana:8000/admin/documents/document/

Django Version: 1.11.13
Python Version: 3.5.2
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'corsheaders',
 'django_extensions',
 'documents.apps.DocumentsConfig',
 'reminders.apps.RemindersConfig',
 'paperless_tesseract.apps.PaperlessTesseractConfig',
 'paperless_text.apps.PaperlessTextConfig',
 'django.contrib.admin',
 'rest_framework',
 'crispy_forms',
 'django_filters']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/force/.local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/force/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/force/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/force/.local/lib/python3.5/site-packages/django/contrib/admin/options.py" in wrapper
  551.                 return self.admin_site.admin_view(view)(*args, **kwargs)

File "/home/force/.local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "/home/force/.local/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "/home/force/.local/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner
  224.             return view(request, *args, **kwargs)

File "/home/force/paperless/src/documents/admin.py" in changelist_view
  216.             cl = self.get_changelist_instance(request)

Exception Type: AttributeError at /admin/documents/document/
Exception Value: 'DocumentAdmin' object has no attribute 'get_changelist_instance'
```

This happened after upgrading to the current version with `git pull` and `./manage.py migrate`. The webserver starts without any problems and all links apart from Documents work fine.

**Comment by danielquinn** [comment]
It looks like you're both running the wrong version of Django.  Paperless upgraded to 2.x some time ago.  Remember that part of the upgrade process is to update project dependencies with pipenv or pip:

pipenv
```bash
cd /path/to/paperless/root
pipenv install
```

pip
```bash
pip install -r /path/to/paperless/root/requirements.txt
```

If you do that, restart the webserver, and there's still a problem, let me know, and if not, please close this issue.

**Comment by danielquinn** [comment]
**Update**: I just realised that the [migration docs](https://paperless.readthedocs.io/en/latest/migrating.html#updates) *didn't actually include a line about updating Python depdendencies*, so yeah, this was my bad, sorry.

Anyway, I've added a note for them now, so if you remember to do the update, I'm reasonably sure you should be ok.

**Comment by Forceu** [comment]
Ah perfect, thank you very much. That did indeed fix the issue

**Comment by danielquinn** [comment]
\o/
