### ISSUE TITLE
Correspondent filter not working

### ISSUE THREAD

**Issue by tsia** [danielquinn/paperless#423]
i just noticed that the Correspondent filter on the right sidebar doesn't seem to work.
when i select one, it adds `?correspondent__id__exact=26` (for example) to the URL but it still shows all documents.
Tags on the other hand seem to work fine.
i am curtently on 2.5.0 (2ef2bf873e7a6d4b833ef7044092d42cf970b56c)

**Comment by Sblop** [comment]
I have the same issue on 2.5.0. This was also an issue on 2.4.0.

**Comment by danielquinn** [comment]
Thanks for pointing this out!  I haven't had a lot of time to devote to Paperless lately, but I wanted to fix this one today.  I've merged the needed changes into `master` so you can do a `git pull` to get the fix, or you can wait 'til later today when I release 2.6.0.
