### ISSUE TITLE
Preview document in browser without downloading

### ISSUE THREAD

**Issue by goose-ws** [danielquinn/paperless#424]
Is there a setting or a way that when clicking on a document, I can (pre)view the PDF in browser without downloading it?

Sorry to open an issue for this, I couldn't find a better medium in which to ask.

**Comment by ddddavidmartin** [comment]
This was actually added somewhat recently. You can set `PAPERLESS_INLINE_DOC="true"` in the config file to achieve this.

**Comment by goose-ws** [comment]
Awesome, thank you!

**Comment by clinis** [comment]
I tried to add `PAPERLESS_INLINE_DOC="true"` but it still downloads the documents. 

I use the Docker installation and tried to add this config on `docker-compose.env` and then also tried on `paperless.conf`.

What am I doing wrong?

**Comment by goose-ws** [comment]
I know for Docker at least, args need to be added without quoes. So `=true` not `="true" `

**Comment by clinis** [comment]
It works! Apparently it was that, thanks
