### ISSUE TITLE
Paperless does not follow Filesystem Hierarchy Standard

### ISSUE THREAD

**Issue by gabrielmongefranco** [danielquinn/paperless#427]
Hello,

In the spirit of keeping compatibility across different Linux and Unix systems, it would be a good idea to follow the [File System Hierarchy Standard](http://www.pathname.com/fhs/) for the Consume and Export directories, both of which are set in multiple places including the Docker file. After reading the FHS, I believe the **best place for the Consume directory would be /var/spool/paperless/** because it consists of files that are to be processed later by an application, just like mail and print spooling. The **second best place would be /var/opt/paperless/consume**. The **best place for the Export directory would be /var/opt/paperless/export**.

Database files and other permanent storage should go somewhere under /var/opt/paperless/<some_name>.

Cached content, if it can be deleted without affecting Paperless, should go under /var/cache/paperless/<some_name>

See [http://www.pathname.com/fhs/pub/fhs-2.3.html](http://www.pathname.com/fhs/pub/fhs-2.3.html) for more information.

Gabriel Mongefranco
Software Developer
[https://gabriel.mongefranco.com](https://gabriel.mongefranco.com)

**Comment by danielquinn** [comment]
Paperless wasn't designed to be a Linux package, but rather a thing you can install without root privileges.  To that end, the values you use for `PAPERLESS_CONSUMPTION_DIR` etc. are the definitive place Paperless will use for doing its thing.  The Docker container is a little more rigid, as it's meant to be a self-contained environment, but as it's a self-contained environment, adherence to the LSHS isn't really a concern.  Sure it would have been a good idea to follow that when we started, but changing it now isn't really worth the hassle.

I've noted that you also posted an issue for proper OS packaging -- for such a case, obviously LSHS support is preferred.  Conveniently, as Paperless defines these values base don environment variables, the packaging process need only have a line like this in `/etc/paperless.conf`:

    PAPERLESS_CONSUMPTION_DIR="/var/spool/paperless/"

Similarly for the database, you can set this in the same file:

    PAPERLESS_DBDIR="/var/opt/paperless/"

I hope this answers your questions.
