### ISSUE TITLE
Apache SSL conf

### ISSUE THREAD

**Issue by GMFalka** [danielquinn/paperless#434]
Hello!

Followed the docs... Got stuck at creating the correct Apache conf file for "https://example.com/paperless".
If i delete the alias line, i can reach the paperless webserver with "https://example.com", but it would be a lot better to reach via "example.com/paperless"

Im not using docker or venv. 
(my other app sites works, like "example.com/nextcloud")

If we can make this work, it might be a good idea to add it to the [apache docs](https://paperless.readthedocs.io/en/latest/setup.html#apache) :)

Heres my _/etc/apache2/sites-enabled/paperless-le-ssl.conf_

```
<IfModule mod_ssl.c>
<VirtualHost *:443>

        ServerName example.com
        ServerAlias www.example.com

    Alias /paperless /home/paperless/paperless/static/
    <Directory /home/paperless/paperless/static>
        Require all granted
    </Directory>

    WSGIScriptAlias / /home/paperless/paperless/src/paperless/wsgi.py
    WSGIDaemonProcess example.com user=paperless group=paperless threads=5 python-path=/home/paperless/paperless/src:/home/paperless/.local/lib/python3.6/site-packages/
    WSGIProcessGroup example.com

    <Directory /home/paperless/paperless/src/paperless>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

     <IfModule mod_headers.c>
          Header always set Strict-Transport-Security "max-age=15768000; preload"
     </IfModule>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined


SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by ovv** [comment]
Hey

I don't know about Apache but there has been some discussion about paperless not really working when using subdirectory. See #253

**Comment by GMFalka** [comment]
Thanks for the link!

I skimped over it, looks like it cant really be done (yet).

Maybe an other solution to bind it to local ip? I think most poeple only care about local network availability anyway.

Anyone know how to edit the OP config for this?
