### ISSUE TITLE
Fails to build docker on macos

### ISSUE THREAD

**Issue by michaelr524** [danielquinn/paperless#437]
I get the following when I run `docker-compose up` on macos. Checked with commit 84511f8418ab65441c69763730c2ff84eab59527 - the issue doesn't exist there, and the build runs fine.

(50/59) Installing libatomic (6.4.0-r9)
(51/59) Installing mpfr3 (3.1.5-r1)
(52/59) Installing mpc1 (1.0.3-r1)
(53/59) Installing gcc (6.4.0-r9)
**ERROR: Failed to create usr/libexec/gcc/x86_64-alpine-linux-musl/6.4.0/cc1obj: I/O error
ERROR: gcc-6.4.0-r9: IO ERROR**
(54/59) Installing musl-dev (1.1.19-r10)
(55/59) Installing libc-dev (0.7.1-r0)
(56/59) Installing g++ (6.4.0-r9)
(57/59) Installing libjpeg-turbo-dev (1.5.3-r3)
(58/59) Installing jpeg-dev (8-r6)

**Comment by danielquinn** [comment]
IO Errors are usually bad news related to a flakey network connection or flakey hardware.  I'm afraid I don't have enough information here to be sure of either.

However, the point at which that's happening is [right here](https://github.com/danielquinn/paperless/blob/master/Dockerfile#L18) where we're adding a few Alpine packages to the container.  Your container is reaching out to the Alpine file servers, downloading packages, and installing them locally.  *Somewhere* in that process you're getting an IO error that's causing your build to die.

I would check the quality of your network connection and your host computer's logs to see if you have any disk errors/failures.  Sorry I can't be more helpful.  You can always just use the container on Docker Hub, but if you've got disk issues, I would try to solve those first.

As this isn't Paperless-specific though, I'm going to close this.
