### ISSUE TITLE
Is it possible to use a Postgis db with Paperless in Docker

### ISSUE THREAD

**Issue by sbrunner** [danielquinn/paperless#445]
Here
https://github.com/danielquinn/paperless/blob/d825667c9bffe615b753451c5ddbe50d693bc978/src/paperless/settings.py#L147-L154
I see that we can configure the username and the password, but we can't change the host shouldn't we add optional `PAPERLESS_DBHOST` and `PAPERLESS_DBPORT`?

**Comment by danielquinn** [comment]
Yup.  That's a good idea.  Send me a PR and I'll add it in when I get a minute!
