### ISSUE TITLE
Date from document title is saved as date -1 day

### ISSUE THREAD

**Issue by scubafly** [danielquinn/paperless#457]
![change_document___paperless](https://user-images.githubusercontent.com/820268/50043521-d1a5fa00-0075-11e9-8c16-ce78c5c25faf.png)

See image.
When uploading a document with a date set in the title is gets that date - 1 day.
I've set the `PAPERLESS_FILENAME_DATE_ORDER` to `DMY`

**Comment by MasterofJOKers** [comment]
This seems to be a timezone issue. As you can see in your output, it detected a date of `2018-08-15T00:00:00+02:00` which corresponds to a UTC time of `2018-08-14T22:00:00+00:00`.

So my guess is, it adds the local timezone automatically in the detection step, but then shows UTC time in the webinterface.

**Comment by scubafly** [comment]
Hmm thnx! I guess I've set the timezone for the consumer docker container, but not for the web container.
I'll try to change this, and let you know if this solves it.
Thanks again!

**Comment by scubafly** [comment]
Setting the timezone on the web container did the trick!
