### ISSUE TITLE
auto rotate landscape documents

### ISSUE THREAD

**Issue by polo2ro** [danielquinn/paperless#47]
Hi,
Is it possible to detect document orientation before OCR? I have tried with a landscape document and i got no valid text out of it, i suppose manually rotate the file before consume will fix it but this is a pain for an automated scan to ocr.

https://tesseract-ocr.github.io/a01281.html#ga16c4b28cadc2160bf18b84c3f897a2d2

**Comment by pitkley** [comment]
Yes, the tools we use seem to be able to do that (as you have linked yourself). I'm going to throw something together and test it, and I'll let you know if it works out!

**Comment by polo2ro** [comment]
cool, thanks!

**Comment by pitkley** [comment]
Okay, seems like an [easy fix](https://github.com/pitkley/paperless/commit/c34d57a872859e8f6799dceb41022b043490c6bd). I tested it with a rotated document and it worked a treat.

Are you able to test it from my [`feature/detect-orientation`](https://github.com/pitkley/paperless/tree/feature/detect-orientation) branch?

**Comment by polo2ro** [comment]
ok i will test it with my document and get back to you

**Comment by polo2ro** [comment]
This worked well, god job

**Comment by pitkley** [comment]
Cool, thanks for the confirmation! I'll get a PR going shortly :+1:

**Comment by pitkley** [comment]
Just an FYI, I have opened PR #49!

**Comment by sirpresage** [comment]
Hi, i installed paperless a few days ago but OCRing landscape documents didn't worked for me. Can you send me a landscape document that works for you so i can identify if it's a config problem on my fresh install ? :)
