### ISSUE TITLE
user to login

### ISSUE THREAD

**Issue by njordr** [danielquinn/paperless#5]
Hi.

I try to follow your readme but "python manage.py consume" does not ecist and I don't know which user to use to login.

Kind regards,
Giovanni

**Comment by danielquinn** [comment]
Sorry about that, I changed the name from `consume` to `document_consumer` and must have forgotten to change the README.  I'll do that now.

As for having a user to login, you need to create one from the command line using `python manage.py createsuperuser`.  Just follow the prompts that come up and you're ready to login.  Obviously, I should add that to the README too.
