### ISSUE TITLE
Had some JPGs in same directory as PDFs, but cannot view them afterwards

### ISSUE THREAD

**Issue by zedster** [danielquinn/paperless#53]
The JPGs seem to have been processed fine, I can see the content from OCR etc. 

But when I click on the (404ed/broken) attachment icon I get an error (copy + pasted below).
Could it be because the scanner saved automatically in capital letters, JPG rather than jpg/jpeg ?

Let me know if there is anything else I can help with.

Environment:

Request Method: GET
Request URL: http://192.168.3.1:8100/fetch/19

Django Version: 1.9
Python Version: 3.4.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'documents',
 'logger']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "/home/seb/.local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/home/seb/.local/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/seb/.local/lib/python3.4/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/seb/.local/lib/python3.4/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/seb/.local/lib/python3.4/site-packages/django/views/generic/detail.py" in get
  119.         return self.render_to_response(context)

File "/home/seb/.paperless/src/documents/views.py" in render_to_response
  31.             content_type=content_types[self.object.file_type]

Exception Type: KeyError at /fetch/19
Exception Value: 'JPG'

**Comment by danielquinn** [comment]
Neat.  I'll take a look and see if I can reproduce this with the `.JPG` naming as you suggest.  Thanks.

**Comment by danielquinn** [comment]
I've reproduced this locally, so I'll try to fix it soon.  For now, I'm afraid you just have to ensure that all files have a lower-case extension.

**Comment by danielquinn** [comment]
Ok, good news, this is finally fixed.  The details for fixing it is in the [pull request](https://github.com/danielquinn/paperless/pull/62) that I just merged, but the short answer is that if you do a `git pull` to update paperless, the shouldn't happen again, but in order to access the files affected by this bug, you have to follow the procedure in outlined there.

I hope this works for you :-)
