### ISSUE TITLE
Have a way to re-apply tag's search terms on already imported documents

### ISSUE THREAD

**Issue by zedster** [danielquinn/paperless#54]
Only after importing 100+ documents did i notice you could setup tags with search words to automatically tag newly processed documents.

When you come round to doing the UI, might be a good to include information on this.

Alternatively the ability to re-run all the tagging rules on existing documents would be very useful.

**Comment by danielquinn** [comment]
Actually there's already a re-tagger, it's just not documented yet :-(

Basically you just setup your tags the way you want them with the right keywords etc. in the admin, and then run:

    $ python manage.py document_retagger

It'll do the rest of the work for you.

I'll leave this issue open as a reminder to get this utility documented.

**Comment by danielquinn** [comment]
Thanks for the heads-up.  I've updated the documentation and when it comes time to do the UI, I'll definitely include a note about using the re-tagger when a new tag is added.
