### ISSUE TITLE
Timestamped and searchable logs

### ISSUE THREAD

**Issue by darkermatter** [danielquinn/paperless#56]
Hi everyone!

I'm trying to track down what may be data loss on import. I am importing around 20000 PDFs which are numbered by sequence. I have noticed that some of the sequences are broken but the overall total in the database appears to be okay. 

Having searchable timestamped logs would really help in identifying possible data loss.

Thanks!

**Comment by the01** [comment]
On that note, I was wondering why you are not using the [logging module](https://docs.python.org/3/library/logging.html)?
That way you could just add a file logger with date/time formatting and there you go..

**Comment by danielquinn** [comment]
@the01 the logging module is probably the right way to go, and the stuff we're using now was a rather quick fix that I implemented without too much thinking.  The truth is that my experience with the logging module is limited, so this way just seemed easier.

I'll keep this issue open as a reminder to look into doing things The Right Way, but if you'd like to offer up some ideas, code snippets, or even a PR, I'd be happy to take a look.

**Comment by danielquinn** [comment]
This has now been fixed.  By default, the logger for document consumption both writes to standard out (so if you're logging the output to a file, you're good to go) as well as pushes the values into the database (which you can query by way of the api (`/api/logs`), use the ORM (`Log.objects.all().by_group()`) or just query the database directly.

I hope this helps :-)
