### ISSUE TITLE
Authentication on the API

### ISSUE THREAD

**Issue by danielquinn** [danielquinn/paperless#59]
The REST API is there, but it's very limited.  There's no authentication, no permissions checking, etc.  I'm not even sure what will happen if you issue a POST or PUT request on any of the three access points (sender, tag, and document).

I'd like to introduce oauth2 and restrict read and write requests to authenticated users.

**Comment by thomasbrueggemann** [comment]
How is the API authentication handled right now?
`/api/auth/login` delivers the login page HTML.

I would like to write an _electron_ client for paperless 🙂

**Comment by thomasbrueggemann** [comment]
Ah, nevermind - just explored that HTTP Basic on the API endpoint works just fine 🤞
Let's get to work then!
