### ISSUE TITLE
Error with dockerfile

### ISSUE THREAD

**Issue by bookmark** [danielquinn/paperless#66]
I try pull code and setup with Docker but it has error , how I can fix it ?

![image](https://cloud.githubusercontent.com/assets/358347/13469112/7620262a-e0d8-11e5-8882-50a0fc1a0da9.png)

**Comment by pitkley** [comment]
Are you running at least [docker-compose v1.6.0](https://github.com/docker/compose/releases/tag/1.6.0)? You can check your version by executing `docker-compose -v`.

**Comment by bookmark** [comment]
My version: docker-compose version 1.5.2, build 7240ff3

**Comment by pitkley** [comment]
That is your issue, you need at least version 1.6.0. See [here](https://docs.docker.com/compose/install/) on how to install the most current version of docker-compose ([1.6.2](https://github.com/docker/compose/releases/tag/1.6.2)) if your operating system doesn't have it in it's packages.

It should reduce to these commands (run as root):

```console
# curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
```

You might have to uninstall your current version first for this to work.

**Comment by danielquinn** [comment]
As an addendum to the link @pitkley provided, I should mention that I updated my version of docker-compose simply by setting it up in a virtualenv.  That way I'm not letting Docker's installation script mangle my local package management:

```bash
$ virtualenv ${HOME}/.virtualenvs/paperless
$ . ${HOME}/.virtualenvs/paperless/bin/activate
$ pip install docker-compose
```

**Comment by danielquinn** [comment]
Since this hasn't had any action in about 24hours, I'm closing this issue.  If @bookmark has more questions, feel free to re-open it.
