### ISSUE TITLE
Introduce a means of detecting & changing OCR language

### ISSUE THREAD

**Issue by danielquinn** [danielquinn/paperless#8]
PR #7 starts paperless down the path of supporting multiple languages, but I'd like to get it to the point where we can scan documents of different languages and have it automatically choose the appropriate language parser for OCR.  I have no idea how to do this of course, so ideas/suggestions are welcome.

**Comment by the01** [comment]
well, the thing with a "wrong" language file (at least it was for english/german) is that the accuracy drops. So you end up with a couple misspelled words. But assuming you have enough correctly spelled ones, it should be possible to guess the right language from that and then rerun the ocr.

I think it might be a good idea though to maybe keep the scan.

**Comment by danielquinn** [comment]
The scan is already kept, so that's not a problem, but the idea of OCR once, then doing it again is a good one.  Do you have any pointers for guessing language based on some text?

**Comment by the01** [comment]
Where do they get saved? I could only find the (empty) '.gpg'

I've played with a google api of that kind before, but sending all that data out into the internet is not the best idea.
A quick search however returned the following python package: https://pypi.python.org/pypi/langdetect
That looks promising.

**Comment by danielquinn** [comment]
If the pdf is being saved as a 0-byte .pdf.gpg file, then there's likely a problem with permissions.  The one time that happened to me, the user running the `consume_documents` script didn't have the rights to read the original PDF.  Here's where that's happening in the consumption script:

```python
with open(pdf, "rb") as unencrypted:
    with open(doc.pdf_path, "wb") as encrypted:
        self._render("  Encrypting", 3)
        encrypted.write(GnuPG.encrypted(unencrypted))
```

If the user running the consumer can read the pdf file, then maybe there's something going on with how GPG is encrypting it?  Regardless, there should probably be a check there to see that the data being written is >0 bytes.  I'll try to add that later.

As for sending the text to Google for guessing, I agree, that's not happening, but langdetect looks like fun.  I'll take a look at it and see what happens.

**Comment by the01** [comment]
Doesn't seem to be a permissions problem, but check or not, if something is not working/failing there should be an error/exception and not just an empty gpg.

Yes, it even provides you with a list of languages and probabilities. Though you would need a dict to map that to the lang codes used by tesseract.

**Comment by danielquinn** [comment]
Alright, I'm working now on a branch to switch out the language based on a sampling as you suggested, and I'll roll in a check for this GPG issue.  You'd think that it should just explode with an exception if it can't read the PDF or something, but failing silently... that's annoying :-(

**Comment by the01** [comment]
great! the reading shouldn't be the problem. that's done by python. maybe gpg has some problems it is not telling me about..

**Comment by danielquinn** [comment]
Ok so I've got good news and bad news:

Good news: I've added language detection.  Just do a `git pull` on the `master` branch and you should be ready to go.  The logic is much like what was discussed here:

1. Parse first with `eng` as the language, and then dump the output of that into `langdetect`.
2. Use a map for ISO639 to convert the two-character codes into three-character ones that play nice with Tesseract.
3. I also had to add a bunch of checks for cases where Tesseract just barfs on languages it might not have been compiled to support.

Bad news: the GPG step comes after the db creation, so I'd have to do an `os.stat()` on the file and then rollback the db in the event that the filesize == 0.  The thing is, in these cases, it's unlikely that it's a failure of GPG or paperless, but more likely a config problem (though I don't know what that might be yet).  It appears that GPG doesn't fail as violently as it should, and in your case it's simply attempting to encrypt something, failing at it, and returning `""`.

So, here's what I'm going to do.  I'm going to close this ticket because the subject of it is now closed.  However, if you can reproduce this problem (with the latest master branch), please open a new ticket with some more information regarding this GPG problem.  Specifically:

* Your Python version (I hope you're using 3.x, 'cause I have no idea what happens on 2.x versions)
* Permissions and ownership on `media/documents/pdf` and `CONSUMPTION_DIR`
* What values you have for the paperless-specific settings variables.
* Whether you can produce the problem running as `root` (if you're comfortable with that)

If I can get this, I can attempt to reproduce the problem on my environment and introduce a fix or check for configuration at start up.
