### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'unpaper'

### ISSUE THREAD

**Issue by skydge** [danielquinn/paperless#85]
Hello guys,

On the Docker built, when I try to consume a PDF, the consumer crash because it is not able to find unpaper.
Complete output below from a fresh install:

$ docker-compose up
Creating network "paperless_default" with the default driver
Creating volume "paperless_media" with default driver
Creating volume "paperless_data" with default driver
Pulling webserver (pitkley/paperless:latest)...
latest: Pulling from pitkley/paperless
fdd5d7827f33: Already exists
a3ed95caeb02: Pull complete
0f35d0fe50cc: Pull complete
627b6479c8f7: Pull complete
67c44324f4e3: Pull complete
9ee7e6ec2a05: Pull complete
8f326541fea8: Pull complete
da5f31d583e4: Pull complete
62ab064c3b82: Pull complete
a3888761f270: Pull complete
1ee52049c504: Pull complete
a0526344e8b7: Pull complete
bf406ab00171: Pull complete
fa9648a54fca: Pull complete
Digest: sha256:9c1ef27e4ee100b9e24bcd005aa0cfcdd29dc1598391ef93c8554d72fe12d6b9
Status: Downloaded newer image for pitkley/paperless:latest
Creating paperless_webserver_1
Creating paperless_consumer_1
Attaching to paperless_webserver_1, paperless_consumer_1
webserver_1 | Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
consumer_1  | Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
webserver_1 | Get:2 http://security.debian.org jessie/updates/main amd64 Packages [273 kB]
webserver_1 | Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
webserver_1 | Ign http://httpredir.debian.org jessie InRelease
consumer_1  | Ign http://httpredir.debian.org jessie InRelease
consumer_1  | Get:2 http://security.debian.org jessie/updates/main amd64 Packages [273 kB]
consumer_1  | Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
consumer_1  | Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
consumer_1  | Get:5 http://httpredir.debian.org jessie Release [148 kB]
consumer_1  | Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [5019 B]
webserver_1 | Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
webserver_1 | Get:5 http://httpredir.debian.org jessie Release [148 kB]
consumer_1  | Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9034 kB]
webserver_1 | Get:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [5019 B]
webserver_1 | Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9034 kB]
consumer_1  | Fetched 9668 kB in 11s (829 kB/s)
consumer_1  | Reading package lists...
consumer_1  | dpkg-query: package 'tesseract-ocr-fra' is not installed and no information is available
consumer_1  | Use dpkg --info (= dpkg-deb --info) to examine archive files,
consumer_1  | and dpkg --contents (= dpkg-deb --contents) to list their contents.
consumer_1  | Reading package lists...
consumer_1  | Building dependency tree...
consumer_1  | Reading state information...
consumer_1  | The following packages were automatically installed and are no longer required:
consumer_1  |   gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0
consumer_1  |   libcairo-gobject2 libcairo-script-interpreter2 libcdt5 libcgraph6 libcroco3
consumer_1  |   libdjvulibre-dev libelfg0 libexif-dev libexif12 libexpat1-dev
consumer_1  |   libfontconfig1-dev libfreetype6-dev libgd3 libgirepository-1.0-1
consumer_1  |   libglib2.0-bin libgraphviz-dev libgvc6 libgvpr2 libice-dev libice6
consumer_1  |   libilmbase-dev libjasper-dev libjbig-dev libjs-excanvas libjs-jquery
consumer_1  |   liblcms2-dev liblqr-1-0-dev liblzo2-2 libmagickcore-6-arch-config
consumer_1  |   libmagickcore-6-headers libmagickwand-6-headers libopenexr-dev libpathplan4
consumer_1  |   libpcre3-dev libpcrecpp0 libpixman-1-dev libpthread-stubs0-dev librsvg2-2
consumer_1  |   librsvg2-common libsm-dev libsm6 libtiff5-dev libtiffxx5 libvpx1 libwmf-dev
consumer_1  |   libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev
consumer_1  |   libxdmcp-dev libxdot4 libxext-dev libxpm4 libxrender-dev libxt-dev libxt6
consumer_1  |   mime-support pkg-config x11-common x11proto-core-dev x11proto-input-dev
consumer_1  |   x11proto-kb-dev x11proto-render-dev x11proto-xext-dev xorg-sgml-doctools
consumer_1  |   xtrans-dev
consumer_1  | Use 'apt-get autoremove' to remove them.
consumer_1  | The following NEW packages will be installed:
consumer_1  |   tesseract-ocr-fra
consumer_1  | 0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
consumer_1  | Need to get 4637 kB of archives.
consumer_1  | After this operation, 26.9 MB of additional disk space will be used.
consumer_1  | Get:1 http://httpredir.debian.org/debian/ jessie/main tesseract-ocr-fra all 3.02-2 [4637 kB]
consumer_1  | debconf: delaying package configuration, since apt-utils is not installed
consumer_1  | Fetched 4637 kB in 4s (1100 kB/s)
consumer_1  | Selecting previously unselected package tesseract-ocr-fra.
(Reading database ... 20267 files and directories currently installed.)
consumer_1  | Preparing to unpack .../tesseract-ocr-fra_3.02-2_all.deb ...
consumer_1  | Unpacking tesseract-ocr-fra (3.02-2) ...
consumer_1  | Setting up tesseract-ocr-fra (3.02-2) ...
webserver_1 | Fetched 9668 kB in 35s (272 kB/s)
webserver_1 | Reading package lists...
webserver_1 | dpkg-query: package 'tesseract-ocr-fra' is not installed and no information is available
webserver_1 | Use dpkg --info (= dpkg-deb --info) to examine archive files,
webserver_1 | and dpkg --contents (= dpkg-deb --contents) to list their contents.
webserver_1 | Reading package lists...
webserver_1 | Building dependency tree...
webserver_1 | Reading state information...
webserver_1 | The following packages were automatically installed and are no longer required:
webserver_1 |   gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0
webserver_1 |   libcairo-gobject2 libcairo-script-interpreter2 libcdt5 libcgraph6 libcroco3
webserver_1 |   libdjvulibre-dev libelfg0 libexif-dev libexif12 libexpat1-dev
webserver_1 |   libfontconfig1-dev libfreetype6-dev libgd3 libgirepository-1.0-1
webserver_1 |   libglib2.0-bin libgraphviz-dev libgvc6 libgvpr2 libice-dev libice6
webserver_1 |   libilmbase-dev libjasper-dev libjbig-dev libjs-excanvas libjs-jquery
webserver_1 |   liblcms2-dev liblqr-1-0-dev liblzo2-2 libmagickcore-6-arch-config
webserver_1 |   libmagickcore-6-headers libmagickwand-6-headers libopenexr-dev libpathplan4
webserver_1 |   libpcre3-dev libpcrecpp0 libpixman-1-dev libpthread-stubs0-dev librsvg2-2
webserver_1 |   librsvg2-common libsm-dev libsm6 libtiff5-dev libtiffxx5 libvpx1 libwmf-dev
webserver_1 |   libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev
webserver_1 |   libxdmcp-dev libxdot4 libxext-dev libxpm4 libxrender-dev libxt-dev libxt6
webserver_1 |   mime-support pkg-config x11-common x11proto-core-dev x11proto-input-dev
webserver_1 |   x11proto-kb-dev x11proto-render-dev x11proto-xext-dev xorg-sgml-doctools
webserver_1 |   xtrans-dev
webserver_1 | Use 'apt-get autoremove' to remove them.
webserver_1 | The following NEW packages will be installed:
webserver_1 |   tesseract-ocr-fra
webserver_1 | 0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
webserver_1 | Need to get 4637 kB of archives.
webserver_1 | After this operation, 26.9 MB of additional disk space will be used.
webserver_1 | Get:1 http://httpredir.debian.org/debian/ jessie/main tesseract-ocr-fra all 3.02-2 [4637 kB]
webserver_1 | debconf: delaying package configuration, since apt-utils is not installed
webserver_1 | Fetched 4637 kB in 4s (1134 kB/s)
webserver_1 | Selecting previously unselected package tesseract-ocr-fra.
(Reading database ... 20267 files and directories currently installed.)
webserver_1 | Preparing to unpack .../tesseract-ocr-fra_3.02-2_all.deb ...
webserver_1 | Unpacking tesseract-ocr-fra (3.02-2) ...
webserver_1 | Setting up tesseract-ocr-fra (3.02-2) ...

consumer_1  | Consuming /consume/myPDF.pdf
consumer_1  | Generating greyscale image from /consume/myPDF.pdf
consumer_1  | multiprocessing.pool.RemoteTraceback:
consumer_1  | """
consumer_1  | Traceback (most recent call last):
consumer_1  |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 119, in worker
consumer_1  |     result = (True, func(*args, **kwds))
consumer_1  |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
consumer_1  |     return list(map(*args))
consumer_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 404, in run_unpaper
consumer_1  |     unpaper, pnm, pnm.replace(".pnm", ".unpaper.pnm")
consumer_1  |   File "/usr/local/lib/python3.5/subprocess.py", line 950, in __init__
consumer_1  |     restore_signals, start_new_session)
consumer_1  |   File "/usr/local/lib/python3.5/subprocess.py", line 1544, in _execute_child
consumer_1  |     raise child_exception_type(errno_num, err_msg)
consumer_1  | FileNotFoundError: [Errno 2] No such file or directory: 'unpaper'
consumer_1  | """
consumer_1  |
consumer_1  | The above exception was the direct cause of the following exception:
consumer_1  |
consumer_1  | Traceback (most recent call last):
consumer_1  |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1  |     execute_from_command_line(sys.argv)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
consumer_1  |     utility.execute()
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
consumer_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
consumer_1  |     self.execute(*args, **cmd_options)
consumer_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
consumer_1  |     output = self.handle(*args, **options)
consumer_1  |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 49, in handle
consumer_1  |     self.loop()
consumer_1  |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 59, in loop
consumer_1  |     self.file_consumer.consume()
consumer_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 122, in consume
consumer_1  |     imgs = self._get_greyscale(tempdir, doc)
consumer_1  |   File "/usr/src/paperless/src/documents/consumer.py", line 159, in _get_greyscale
consumer_1  |     pool.map(run_unpaper, itertools.product([self.UNPAPER], pnms))
consumer_1  |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 260, in map
consumer_1  |     return self._map_async(func, iterable, mapstar, chunksize).get()
consumer_1  |   File "/usr/local/lib/python3.5/multiprocessing/pool.py", line 608, in get
consumer_1  |     raise self._value
consumer_1  | FileNotFoundError: [Errno 2] No such file or directory: 'unpaper'
paperless_consumer_1 exited with code 0

$ docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013

$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:59:07 2016
 OS/Arch:      linux/amd64

running inside Ubuntu 15.10.

I'm still new to Docker and this project, I'm not sure where to look to fix the issue myself, but I'm trying in the meantime ;o)

Thank you for your help!
Kind regards,
David

**Comment by danielquinn** [comment]
Hi David, it looks like the Docker installation you're using doesn't automatically install unpaper for some reason.  Are you sure you're running the latest copy of Paperless?  The `Dockerfile` in the master repo [has had `unpaper` in the list of packages to install](https://github.com/danielquinn/paperless/blob/master/Dockerfile#L8) for some time now.

It's also possible that you had it working for a while, and since we've added unpaper to the list of dependencies, your Docker instance (as it was built before the dependency was added) doesn't have it.  I'd recommend blowing away your old docker images and re-building using `docker-compose up -d`.  This should execute the provisioning script that will install unpaper in your Docker image, so when your setup comes back online, you should have everything you need.

Does that make sense?  I'm sorry, but Docker and I are still new acquaintances.

**Comment by pitkley** [comment]
Nah, that is a issue on my end. Fixing up the image on Docker Hub right now, will keep you guys updated!

**Comment by pitkley** [comment]
An updated image is available on Docker Hub. @skydge can you `docker pull pitkley/paperless` and try again?

**Comment by skydge** [comment]
Digest: sha256:85cb96c55eeb8079dfc22f3a1ce7db162ad33a79aa998f48a1a0f83c6aab7ae9
Status: Downloaded newer image for pitkley/paperless:latest

And working! Thank you so much @pitkley ;
@danielquinn you can close this one too. Thanks for your help.

I'm looking forward to play with Paperless, this is just awesome !!
