### ISSUE TITLE
Allow Matching on Correspondents

### ISSUE THREAD

**Issue by stringlytyped** [danielquinn/paperless#89]
I love the ability to automatically assign tags based on a document's OCR'd text. However, I am finding myself creating tags for different companies:

![paperless screenshot](https://cloud.githubusercontent.com/assets/1239396/13897296/0186bfec-ed6a-11e5-9eeb-6951d04d625a.png)

In the above screenshot, the _extra_foods_, _staples_ and _ikea_ tags are automatically added to receipts issued by those stores. Ideally, they should be correspondents instead of tags.

It would be great if it were possible to assign correspondents to a document from matched text, the same way you can assign tags.

**Comment by danielquinn** [comment]
I've been considering this very thing actually.  I was going to add this feature as part of #81 since I wanted to refactor how tagging worked for that issue as well.  So the short answer is: "I totally agree and I'm going to do this soon".
