### ISSUE TITLE
Label/Tag

### ISSUE THREAD

**Issue by the01** [danielquinn/paperless#9]
I think it would be a good idea to add some kind of label or tags.
That way one could give the electric bill for example: BILL, ELECTRIC
Or if it is for your mothers computer: BILL, COMPUTER, MOM,..
Some bills might be too long for a single scan and that way it is possible to group those a little at least.

With a little machine learning that could be done automatically I suppose.

**Comment by avichalp** [comment]
I think its a good idea to implement tags. It will make bills easily searchable and accessible. I will try to submit a PR as soon as I get some time.

**Comment by danielquinn** [comment]
The thing about tagging is that they have to be managed manually which sort of defeats the whole purpose of "scan now and search later".  But so long as it doesn't interfere with this premise I'm not opposed to adding it.

**Comment by danielquinn** [comment]
Ok I've added basic label (and colours!) support.  Unfortunately, the colours aren't easy to discern because you have to select them based on their hex value, but this should be ok for now.  Do a `git pull origin master` for the latest and then run `python manage.py migrate`.

**Comment by the01** [comment]
@managed manually: that is just the first step. It should not be too hard to add a simple keyword based classifier (or some ML technique) to automatically tag the scans.

Cool! I'm a little short on time right now, but I will have a look later.
