### ISSUE TITLE
Detect already imported documents

### ISSUE THREAD

**Issue by timwhite** [danielquinn/paperless#97]
It would be great if we detect a document had already been imported. Something as simple as storing the checksum of the original document (I assume we store the original encrypted in the DB, and not a processed version), and then checking the checksum before we consume a document.

A simple way of dealing with them in the consumption would be to move the duplicate document to a "duplicates" subdirectory, rather than importing it again.

Use case, I'm not sure if all these old PDF's from this USB I found got processed into the system, lets put them in the consumption system again and if they already exist, then I know it's safe to delete the from this USB.

**Comment by danielquinn** [comment]
Hmm.  Yeah this doesn't sound too tough to do either.  Basically all that's required is a `checksum` field on the `Document` model and then a minor change to the consumer script.

I'll add it to the list, but if you want to issue a PR yourself, I'm happy to field it.

**Comment by timwhite** [comment]
@danielquinn Thank you for implementing this!

**Comment by danielquinn** [comment]
You're welcome :-)
